# Generated by Django 5.2.6 on 2025-09-30 05:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'estados_turno',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tipos_actividad',
            },
        ),
        migrations.CreateModel(
            name='TipoAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('BENTONITA', 'Bentonita'), ('POLIMEROS', 'Polímeros'), ('CMC', 'CMC'), ('SODA_ASH', 'Soda Ash'), ('DISPERSANTE', 'Dispersante'), ('LUBRICANTE', 'Lubricante'), ('ESPUMANTE', 'Espumante')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tipos_aditivo',
            },
        ),
        migrations.CreateModel(
            name='TipoComplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('BROCA', 'Broca'), ('REAMING_SHELL', 'Reaming Shell'), ('ZAPATA', 'Zapata'), ('CORE_LIFTER', 'Core Lifter')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tipos_complemento',
            },
        ),
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tipo_turnos',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'unidades_medida',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_contract_admin', models.BooleanField(default=False)),
                ('is_system_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contrato', models.CharField(max_length=200)),
                ('duracion_turno', models.PositiveIntegerField(default=8)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='drilling.cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='drilling.contrato'),
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='OPERATIVO', max_length=20)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='drilling.contrato')),
            ],
            options={
                'db_table': 'maquinas',
            },
        ),
        migrations.CreateModel(
            name='Sondaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sondaje', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('3000.00'))])),
                ('inclinacion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-90.00')), django.core.validators.MaxValueValidator(Decimal('90.00'))])),
                ('cota_collar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sondajes', to='drilling.contrato')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sondajes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sondaje',
                'verbose_name_plural': 'Sondajes',
                'db_table': 'sondajes',
            },
        ),
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('codigo_producto', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField()),
                ('familia', models.CharField(choices=[('PRODUCTOS_DIAMANTADOS', 'Productos Diamantados'), ('ADITIVOS_PERFORACION', 'Aditivos de Perforación'), ('CONSUMIBLES', 'Consumibles'), ('REPUESTOS', 'Repuestos')], max_length=30)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('numero_guia', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimientos', to='drilling.contrato')),
                ('tipo_aditivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drilling.tipoaditivo')),
                ('tipo_complemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drilling.tipocomplemento')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.unidadmedida')),
            ],
            options={
                'verbose_name': 'Abastecimiento',
                'verbose_name_plural': 'Abastecimientos',
                'db_table': 'abastecimiento',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(choices=[('OPERADOR_SENIOR', 'Operador Senior'), ('OPERADOR', 'Operador'), ('AYUDANTE', 'Ayudante'), ('SUPERVISOR', 'Supervisor'), ('MECANICO', 'Mecánico'), ('GEOLOGO', 'Geólogo')], max_length=30)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='drilling.contrato')),
            ],
            options={
                'db_table': 'trabajadores',
                'unique_together': {('contrato', 'rut')},
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETADO', 'Completado'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_creados', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='drilling.maquina')),
                ('sondaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='drilling.sondaje')),
                ('tipo_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.tipoturno')),
            ],
            options={
                'db_table': 'turnos',
                'unique_together': {('sondaje', 'maquina', 'fecha', 'tipo_turno')},
            },
        ),
        migrations.CreateModel(
            name='ConsumoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('serie_utilizada', models.CharField(blank=True, max_length=50)),
                ('metros_inicio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('metros_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('metros_utilizados', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True)),
                ('estado_final', models.CharField(choices=[('OPTIMO', 'Óptimo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('DESGASTADO', 'Desgastado'), ('INUTILIZABLE', 'Inutilizable')], default='OPTIMO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abastecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.abastecimiento')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='drilling.turno')),
            ],
            options={
                'verbose_name': 'Consumo de Stock',
                'verbose_name_plural': 'Consumos de Stock',
                'db_table': 'consumo_stock',
            },
        ),
        migrations.CreateModel(
            name='TurnoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tiempo_calc', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.tipoactividad')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='drilling.turno')),
            ],
            options={
                'db_table': 'turno_actividad',
            },
        ),
        migrations.CreateModel(
            name='TurnoAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_perforados', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avance', to='drilling.turno')),
            ],
            options={
                'db_table': 'turno_avance',
            },
        ),
        migrations.CreateModel(
            name='TurnoComplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_serie', models.CharField(max_length=100)),
                ('metros_inicio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metros_fin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metros_turno_calc', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('tipo_complemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.tipocomplemento')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementos', to='drilling.turno')),
            ],
            options={
                'db_table': 'turno_complemento',
            },
        ),
        migrations.CreateModel(
            name='TurnoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('horas_trabajadas_calc', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('estado_bomba', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('DEFICIENTE', 'Deficiente'), ('INOPERATIVO', 'Inoperativo')], max_length=20)),
                ('estado_unidad', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('DEFICIENTE', 'Deficiente'), ('INOPERATIVO', 'Inoperativo')], max_length=20)),
                ('estado_rotacion', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('DEFICIENTE', 'Deficiente'), ('INOPERATIVO', 'Inoperativo')], max_length=20)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maquina_estado', to='drilling.turno')),
            ],
            options={
                'db_table': 'turno_maquina',
            },
        ),
        migrations.CreateModel(
            name='TurnoAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_aditivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.tipoaditivo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='drilling.turno')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.unidadmedida')),
            ],
            options={
                'db_table': 'turno_aditivo',
            },
        ),
        migrations.AddField(
            model_name='tipoaditivo',
            name='unidad_medida_default',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.unidadmedida'),
        ),
        migrations.CreateModel(
            name='TurnoCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrida_numero', models.PositiveIntegerField()),
                ('desde', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hasta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_calc', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('longitud_testigo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_recuperacion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('pct_retorno_agua', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('litologia', models.TextField()),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='drilling.turno')),
            ],
            options={
                'db_table': 'turno_corrida',
                'unique_together': {('turno', 'corrida_numero')},
            },
        ),
        migrations.CreateModel(
            name='TurnoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('OPERADOR_PRINCIPAL', 'Operador Principal'), ('OPERADOR_APOYO', 'Operador de Apoyo'), ('AYUDANTE', 'Ayudante'), ('SUPERVISOR', 'Supervisor'), ('MECANICO', 'Mecánico')], max_length=30)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.trabajador')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores_turno', to='drilling.turno')),
            ],
            options={
                'db_table': 'turno_trabajador',
                'unique_together': {('turno', 'trabajador')},
            },
        ),
    ]
