# Generated by Django 5.2.6 on 2025-10-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimiento',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sondaje',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='created_by',
        ),
    ]
