# Generated by Django 5.2.6 on 2025-10-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('drilling', '0002_remove_abastecimiento_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_contract_admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN_SISTEMA', 'Administrador del Sistema'), ('MANAGER_CONTRATO', 'Manager de Contrato'), ('SUPERVISOR', 'Supervisor de Operaciones'), ('OPERADOR', 'Operador Regular')], default='OPERADOR', help_text='Define los permisos y accesos del usuario', max_length=20, verbose_name='Rol del usuario'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato al que pertenece este usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='drilling.contrato', verbose_name='Contrato asignado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_system_admin',
            field=models.BooleanField(default=False, help_text='Marca si este usuario es administrador de todo el sistema', verbose_name='Es administrador del sistema'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Última vez que el usuario accedió al sistema', null=True, verbose_name='Última actividad'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='drilling_cu_role_8539a8_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['contrato'], name='drilling_cu_contrat_18aee5_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_system_admin'], name='drilling_cu_is_syst_028add_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_activity'], name='drilling_cu_last_ac_11d305_idx'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
