# Generated by Django 5.2.6 on 2025-10-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoactividad',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnoactividad',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnomaquina',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnomaquina',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
