# Generated by Django 5.2.6 on 2025-10-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0004_alter_turnoactividad_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETADO', 'Completado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20),
        ),
    ]
