# Generated by Django 5.2.6 on 2025-10-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0005_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='actividades',
            field=models.ManyToManyField(blank=True, related_name='contratos', to='drilling.tipoactividad'),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
