# Generated by Django 5.2.6 on 2025-10-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0007_tipoactividad_tipo_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('STAND_BY_CLIENTE', 'Stand By Cliente'), ('STAND_BY_ROCK_DRILL', 'Stand By Rock Drill'), ('INOPERATIVO', 'Inoperativo'), ('OTROS', 'Otros')], default='OTROS', max_length=30),
        ),
    ]
