# Generated by Django 5.2.6 on 2025-10-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0009_alter_tipoactividad_tipo_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('STAND_BY_CLIENTE', 'Stand By Cliente'), ('STAND_BY_ROCKDRILL', 'Stand By Rock Drill'), ('INOPERATIVO', 'Inoperativo'), ('OPERATIVO', 'Operativo'), ('OTROS', 'Otros')], default='OTROS', max_length=32),
        ),
    ]
