# Generated by Django 5.0.7 on 2025-10-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0010_alter_tipoactividad_tipo_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(choices=[('RESIDENTE', 'Residente'), ('ASISTENTE RESIDENTE', 'Asistente Residente'), ('INGENIERO(A) SEGURIDAD', 'Ingeniero Seguridad'), ('SUPERVISOR(A) SEGURIDAD', 'Supervisor(a) Seguridad'), ('ADMINISTRADOR(A)', 'Administrador(a)'), ('TÉCNICO(A) MECÁCNICO', 'Técnico Mecánico'), ('PERFORISTA DDH', 'Perforista DDH'), ('AYUDANTE', 'Ayudante DDH')], max_length=30),
        ),
        migrations.AlterField(
            model_name='turnotrabajador',
            name='funcion',
            field=models.CharField(choices=[('PERFORISTA', 'Perforista'), ('AYUDANTE', 'Ayudante')], max_length=30),
        ),
    ]
