# Generated by Django 5.0.7 on 2025-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0011_alter_trabajador_cargo_alter_turnotrabajador_funcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AlterUniqueTogether(
            name='trabajador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='rut',
        ),
    ]
