# Generated by Django 5.0.7 on 2025-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0012_rename_nombre_trabajador_nombres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='horometro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
