# Generated by Django 5.0.7 on 2025-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0015_turnosondaje_metros'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turno',
            name='sondajes',
            field=models.ManyToManyField(blank=True, related_name='turnos', through='drilling.TurnoSondaje', to='drilling.sondaje'),
        ),
        migrations.RemoveField(
            model_name='turno',
            name='sondaje',
        ),
    ]
