# Generated by Django 5.0.7 on 2025-10-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0016_alter_turno_unique_together_turno_sondajes_and_more'),
        ('drilling', '0017_populate_complemento_aditivo_sondaje'),
    ]

    operations = [
    ]
