# Generated by Django 5.0.7 on 2025-10-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0018_merge_20251030_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('contrato_text', models.CharField(blank=True, db_column='contrato', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Contrato Actividad',
                'verbose_name_plural': 'Contratos Actividades',
                'db_table': 'contratos_actividades',
                'managed': False,
            },
        ),
        # We only need to update Django's model state to reflect the new
        # `through` relationship. The actual DB table `contratos_actividades`
        # already exists (legacy) and we must not try to recreate/alter it.
        #
        # Use SeparateDatabaseAndState with no database operations and a
        # state-only AlterField so migrations won't attempt to change the DB
        # representation of the M2M (which would fail because altering M2M
        # types is not supported).
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='contrato',
                    name='actividades',
                    field=models.ManyToManyField(blank=True, related_name='contratos', through='drilling.ContratoActividad', to='drilling.tipoactividad'),
                ),
            ],
        ),
    ]
