# Generated by Django 5.0.7 on 2025-11-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0021_alter_turno_unique_together_add_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.RenameIndex(
            model_name='turno',
            new_name='turnos_contrat_6d9062_idx',
            old_name='turnos_contrato_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='turno',
            new_name='turnos_maquina_7f07ab_idx',
            old_name='turnos_maquina_fecha_idx',
        ),
    ]
