# Generated by Django 5.0.7 on 2025-11-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0022_alter_trabajador_dni_pk'),
        ('drilling', '0022_alter_turno_options_and_more'),
    ]

    operations = [
    ]
