# Generated by Django 5.0.7 on 2025-11-14 19:46

from django.db import migrations, models


def _noop(apps, schema_editor):
    # placeholder no-op for reversible RunPython if needed
    return


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0023_merge_20251114_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnomaquina',
            name='horometro_fin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='turnomaquina',
            name='horometro_inicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        # Drop dependent SQL views that reference the column before altering its type
        migrations.RunSQL(
            sql="""
            DROP VIEW IF EXISTS public.vw_turno_sondaje_agg CASCADE;
            DROP VIEW IF EXISTS public.vw_turno_sondaje CASCADE;
            DROP VIEW IF EXISTS public.vw_turno_complementos CASCADE;
            DROP VIEW IF EXISTS public.vw_turnos_detalle CASCADE;
            DROP VIEW IF EXISTS public.vw_trabajadores CASCADE;
            DROP VIEW IF EXISTS public.vw_contrato_actividad CASCADE;
            DROP VIEW IF EXISTS public.vw_abastecimiento_clean CASCADE;
            """,
            reverse_sql="""
            -- reverse: recreate views (will be provided by subsequent RunSQL)
            """,
        ),

        migrations.AlterField(
            model_name='turnomaquina',
            name='horas_trabajadas_calc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),

        # Not recreating views here. The Neon view scripts are managed separately.
    ]
