# Generated by Django 5.0.7 on 2025-11-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0024_turnomaquina_horometro_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='codigo_centro_costo',
            field=models.CharField(blank=True, help_text='Código del centro de costo para APIs de Vilbragroup (ej: 000003)', max_length=50, null=True, verbose_name='Código Centro de Costo'),
        ),
    ]
