# Generated by Django 5.0.7 on 2025-11-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0025_contrato_codigo_centro_costo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoaditivo',
            options={'verbose_name': 'Tipo de Aditivo', 'verbose_name_plural': 'Tipos de Aditivo'},
        ),
        migrations.AlterModelOptions(
            name='tipocomplemento',
            options={'verbose_name': 'Tipo de Complemento', 'verbose_name_plural': 'Tipos de Complemento'},
        ),
        migrations.AddField(
            model_name='tipoaditivo',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código del aditivo desde API Vilbragroup', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipoaditivo',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aditivos', to='drilling.contrato'),
        ),
        migrations.AddField(
            model_name='tipocomplemento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código del producto desde API Vilbragroup', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipocomplemento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_diamantados', to='drilling.contrato'),
        ),
        migrations.AddField(
            model_name='tipocomplemento',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_USO', 'En Uso'), ('DESCARTADO', 'Descartado')], default='NUEVO', help_text='Estado del producto diamantado', max_length=20),
        ),
        migrations.AddField(
            model_name='tipocomplemento',
            name='serie',
            field=models.CharField(blank=True, help_text='Serie única del producto desde API', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoaditivo',
            name='categoria',
            field=models.CharField(blank=True, choices=[('BENTONITA', 'Bentonita'), ('POLIMEROS', 'Polímeros'), ('CMC', 'CMC'), ('SODA_ASH', 'Soda Ash'), ('DISPERSANTE', 'Dispersante'), ('LUBRICANTE', 'Lubricante'), ('ESPUMANTE', 'Espumante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tipoaditivo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoaditivo',
            name='unidad_medida_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drilling.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='tipocomplemento',
            name='categoria',
            field=models.CharField(blank=True, choices=[('BROCA', 'Broca'), ('REAMING_SHELL', 'Reaming Shell'), ('ZAPATA', 'Zapata'), ('CORE_LIFTER', 'Core Lifter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tipocomplemento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tipoaditivo',
            index=models.Index(fields=['codigo'], name='tipos_aditi_codigo_b82591_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoaditivo',
            index=models.Index(fields=['contrato'], name='tipos_aditi_contrat_d70478_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoaditivo',
            index=models.Index(fields=['contrato', 'codigo'], name='tipos_aditi_contrat_4f0a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocomplemento',
            index=models.Index(fields=['codigo'], name='tipos_compl_codigo_b84a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocomplemento',
            index=models.Index(fields=['serie'], name='tipos_compl_serie_b5b252_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocomplemento',
            index=models.Index(fields=['estado'], name='tipos_compl_estado_60ad8b_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocomplemento',
            index=models.Index(fields=['contrato'], name='tipos_compl_contrat_b16db3_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocomplemento',
            index=models.Index(fields=['contrato', 'estado'], name='tipos_compl_contrat_088845_idx'),
        ),
    ]
