# Generated by Django 5.0.7 on 2025-11-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0026_alter_tipoaditivo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CESADO', 'Cesado')], default='ACTIVO', help_text='Estado principal del trabajador', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='subestado',
            field=models.CharField(choices=[('EN_OPERACION', 'En Operación'), ('DESCANSO_MEDICO', 'Descanso Médico'), ('DIAS_LIBRES', 'Días Libres'), ('FALTA', 'Falta')], default='EN_OPERACION', help_text='Estado operacional del trabajador', max_length=30),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['estado'], name='trabajadore_estado_1a4a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['subestado'], name='trabajadore_subesta_0fde56_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['contrato', 'estado'], name='trabajadore_contrat_8d72ae_idx'),
        ),
    ]
