# Generated by Django 5.0.7 on 2025-11-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0027_trabajador_estado_trabajador_subestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='emo_estado',
            field=models.CharField(blank=True, help_text='Estado del examen médico ocupacional', max_length=20, verbose_name='Estado EMO'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='emo_fecha_realizado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha EMO realizado'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='emo_fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento EMO'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fotocheck_fecha_caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha caducidad fotocheck'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fotocheck_fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha emisión fotocheck'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['fotocheck_fecha_caducidad'], name='trabajadore_fotoche_5f841d_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['emo_fecha_vencimiento'], name='trabajadore_emo_fec_b97e5f_idx'),
        ),
    ]
