# Generated by Django 5.0.7 on 2025-11-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0028_trabajador_emo_estado_trabajador_emo_fecha_realizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='area',
            field=models.CharField(blank=True, help_text='Área de trabajo del trabajador', max_length=100, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='emo_programacion',
            field=models.DateField(blank=True, help_text='Fecha programada para próximo examen médico', null=True, verbose_name='Programación EMO'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['emo_programacion'], name='trabajadore_emo_pro_e2ca0d_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['area'], name='trabajadore_area_c043b3_idx'),
        ),
    ]
