# Generated by Django 5.0.7 on 2025-11-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0029_trabajador_area_trabajador_emo_programacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del cargo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='drilling.cargo', verbose_name='Cargo'),
        ),
    ]
