# Generated by Django 5.0.7 on 2025-11-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0030_cargo_alter_trabajador_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='id',
        ),
        migrations.AddField(
            model_name='cargo',
            name='id_cargo',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID Cargo'),
            preserve_default=False,
        ),
    ]
