# Generated by Django 5.0.7 on 2025-11-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0031_remove_cargo_id_cargo_id_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='is_active',
        ),
    ]
