# Generated by Django 5.0.7 on 2025-11-20 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0032_remove_trabajador_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='es_cobrable',
            field=models.BooleanField(default=True, verbose_name='Es cobrable'),
        ),
        migrations.CreateModel(
            name='MaquinaTransferenciaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('contrato_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='drilling.contrato')),
                ('contrato_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='drilling.contrato')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='drilling.maquina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia de Máquina',
                'verbose_name_plural': 'Transferencias de Máquinas',
                'db_table': 'maquina_transferencia_historial',
                'ordering': ['-fecha_transferencia'],
            },
        ),
    ]
