# Generated by Django 5.0.7 on 2025-11-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0033_add_es_cobrable_to_tipoactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='es_cobrable',
            field=models.BooleanField(default=False, verbose_name='Es cobrable'),
        ),
        migrations.CreateModel(
            name='ConfiguracionHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_minimos', models.DecimalField(decimal_places=2, help_text='Metraje mínimo del turno para otorgar hora extra', max_digits=6, verbose_name='Metraje mínimo (m)')),
                ('horas_extra', models.DecimalField(decimal_places=2, default=1.0, help_text='Cantidad de horas extra que se otorgarán', max_digits=4, verbose_name='Horas extra a otorgar')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio vigencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin vigencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_hora_extra', to='drilling.contrato')),
                ('maquina', models.ForeignKey(blank=True, help_text='Dejar vacío para aplicar a todas las máquinas del contrato', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_hora_extra', to='drilling.maquina')),
            ],
            options={
                'verbose_name': 'Configuración de Hora Extra',
                'verbose_name_plural': 'Configuraciones de Horas Extras',
                'db_table': 'configuracion_hora_extra',
                'ordering': ['contrato', 'maquina', '-metros_minimos'],
                'unique_together': {('contrato', 'maquina')},
            },
        ),
    ]
