# Generated by Django 5.0.7 on 2025-11-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0034_add_configuracion_hora_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_extra', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Horas extra otorgadas')),
                ('metros_turno', models.DecimalField(decimal_places=2, help_text='Metraje que generó las horas extras', max_digits=6, verbose_name='Metraje del turno (m)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuracion_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drilling.configuracionhoraextra', verbose_name='Configuración aplicada')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extras', to='drilling.trabajador')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extras', to='drilling.turno')),
            ],
            options={
                'verbose_name': 'Hora Extra de Turno',
                'verbose_name_plural': 'Horas Extras de Turnos',
                'db_table': 'turno_hora_extra',
                'ordering': ['-turno__fecha', 'trabajador__apellidos'],
                'unique_together': {('turno', 'trabajador')},
            },
        ),
    ]
