# Generated by Django 5.0.7 on 2025-11-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0035_turnohoraextra'),
    ]

    operations = [
    ]
