# Generated by Django 5.0.7 on 2025-11-21 20:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0036_add_auto_horas_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(help_text='Año del mes operativo', verbose_name='Año')),
                ('mes', models.IntegerField(help_text='Mes operativo (1-12). El período será del 26 del mes anterior al 25 de este mes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Dejar vacío para usar mes operativo estándar (26-25)', null=True, verbose_name='Fecha inicio (personalizada)')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar vacío para usar mes operativo estándar (26-25)', null=True, verbose_name='Fecha fin (personalizada)')),
                ('meta_metros', models.DecimalField(decimal_places=2, help_text='Metraje objetivo para el período', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Meta en metros')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre la meta (ej: "Meta ajustada por mantenimiento")', verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para desactivar la meta sin eliminarla', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_maquinas', to='drilling.contrato', verbose_name='Contrato')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='drilling.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Meta de Máquina',
                'verbose_name_plural': 'Metas de Máquinas',
                'db_table': 'meta_maquina',
                'ordering': ['-año', '-mes', 'contrato', 'maquina'],
                'indexes': [models.Index(fields=['contrato', 'año', 'mes'], name='meta_maquin_contrat_2933de_idx'), models.Index(fields=['maquina', 'año', 'mes'], name='meta_maquin_maquina_f8b1a8_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='meta_maquin_fecha_i_902eb4_idx'), models.Index(fields=['activo'], name='meta_maquin_activo_7ab276_idx')],
            },
        ),
    ]
