# Generated by Django 5.0.7 on 2025-11-21 21:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0037_add_meta_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='metamaquina',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Servicio/actividad para valorización (vincula con precio unitario)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='drilling.tipoactividad', verbose_name='Servicio'),
        ),
        migrations.CreateModel(
            name='PrecioUnitarioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por metro perforado en la moneda del contrato', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario (PU)')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('BOB', 'Bolivianos (BOB)'), ('PEN', 'Soles (PEN)')], default='USD', max_length=3, verbose_name='Moneda')),
                ('fecha_inicio_vigencia', models.DateField(help_text='Desde cuándo aplica este precio', verbose_name='Fecha inicio vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Hasta cuándo aplica (dejar vacío si es indefinido)', null=True, verbose_name='Fecha fin vigencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_unitarios', to='drilling.contrato', verbose_name='Contrato')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('servicio', models.ForeignKey(help_text='Tipo de actividad/servicio a valorizar', on_delete=django.db.models.deletion.CASCADE, related_name='precios_unitarios', to='drilling.tipoactividad', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Precio Unitario de Servicio',
                'verbose_name_plural': 'Precios Unitarios de Servicios',
                'db_table': 'precio_unitario_servicio',
                'ordering': ['-fecha_inicio_vigencia', 'contrato', 'servicio'],
                'indexes': [models.Index(fields=['contrato', 'servicio', 'activo'], name='precio_unit_contrat_6e936e_idx'), models.Index(fields=['fecha_inicio_vigencia', 'fecha_fin_vigencia'], name='precio_unit_fecha_i_37f08e_idx')],
                'unique_together': {('contrato', 'servicio', 'fecha_inicio_vigencia')},
            },
        ),
    ]
