# Generated by Django 5.0.7 on 2025-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0038_add_valorizacion_metas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_token',
            field=models.CharField(blank=True, help_text='Token único para activar la cuenta', max_length=100, null=True, verbose_name='Token de activación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_account_active',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha activado su cuenta mediante el enlace de activación', verbose_name='Cuenta activada'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_created_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se generó el token de activación o recuperación', null=True, verbose_name='Fecha de creación del token'),
        ),
    ]
