# Generated by Django 5.0.7 on 2025-11-26 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0039_customuser_activation_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nivel_jerarquico', 'nombre'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_superior',
            field=models.ForeignKey(blank=True, help_text='Cargo al que reporta este cargo en la jerarquía', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='drilling.cargo', verbose_name='Cargo Superior'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='nivel_jerarquico',
            field=models.IntegerField(default=99, help_text='Nivel en el organigrama (1=más alto como RESIDENTE, 99=más bajo)', verbose_name='Nivel Jerárquico'),
        ),
    ]
