# Generated by Django 5.0.7 on 2025-11-26 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0040_alter_cargo_options_cargo_cargo_superior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='maquina_asignada',
            field=models.ForeignKey(blank=True, help_text='Máquina a la que está asignado el trabajador (perforistas/ayudantes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_asignados', to='drilling.maquina', verbose_name='Máquina Asignada'),
        ),
    ]
