# Generated by Django 5.0.7 on 2025-11-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0041_trabajador_maquina_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='guardia_asignada',
            field=models.CharField(blank=True, choices=[('A', 'Guardia A'), ('B', 'Guardia B'), ('C', 'Guardia C')], help_text='⚠️ SOLO PARA ORGANIGRAMA - Guardia A, B o C para visualización', max_length=1, null=True, verbose_name='Guardia (Organigrama)'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='maquina_asignada',
            field=models.ForeignKey(blank=True, help_text='⚠️ SOLO PARA ORGANIGRAMA - No afecta asignaciones operativas reales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_asignados', to='drilling.maquina', verbose_name='Máquina Asignada (Organigrama)'),
        ),
    ]
