# Generated by Django 5.0.7 on 2025-11-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0042_trabajador_guardia_asignada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta'), ('COMBI', 'Combi'), ('MINIBUS', 'Minibús'), ('STATION_WAGON', 'Station Wagon'), ('PICKUP', 'Pickup'), ('OTRO', 'Otro')], default='CAMIONETA', max_length=30)),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('año', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('kilometraje', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kilometraje (km)')),
                ('capacidad_pasajeros', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad de pasajeros')),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='OPERATIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='drilling.contrato')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['placa'],
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='vehiculo_asignado',
            field=models.ForeignKey(blank=True, help_text='⚠️ SOLO PARA ORGANIGRAMA - Vehículo asignado especialmente para conductores', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores_asignados', to='drilling.vehiculo', verbose_name='Vehículo Asignado (Organigrama)'),
        ),
    ]
