# Generated by Django 5.0.7 on 2025-11-26 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0043_add_vehiculo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha de mantenimiento')),
                ('kilometraje', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kilometraje en el mantenimiento')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('RUTINARIO', 'Rutinario'), ('EMERGENCIA', 'Emergencia')], default='PREVENTIVO', max_length=20, verbose_name='Tipo de mantenimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo realizado')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo del mantenimiento')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor/Taller')),
                ('repuestos_utilizados', models.TextField(blank=True, help_text='Lista de repuestos o partes reemplazadas', verbose_name='Repuestos utilizados')),
                ('proximo_mantenimiento_sugerido_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Próximo mantenimiento sugerido (km)')),
                ('responsable', models.CharField(blank=True, help_text='Persona que autorizó o supervisó el mantenimiento', max_length=200, verbose_name='Responsable')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mantenimiento de Vehículo',
                'verbose_name_plural': 'Mantenimientos de Vehículos',
                'db_table': 'mantenimiento_vehiculo',
                'ordering': ['-fecha_mantenimiento', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='kilometraje',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kilometraje acumulado del vehículo', max_digits=10, verbose_name='Kilometraje Actual (km)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='proximo_mantenimiento_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilometraje programado para el próximo mantenimiento', max_digits=10, null=True, verbose_name='Próximo mantenimiento (km)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ultimo_mantenimiento_fecha',
            field=models.DateField(blank=True, help_text='Fecha del último mantenimiento realizado', null=True, verbose_name='Fecha último mantenimiento'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ultimo_mantenimiento_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilometraje registrado en el último mantenimiento', max_digits=10, null=True, verbose_name='Kilometraje último mantenimiento'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['estado'], name='vehiculos_estado_bf04b7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['contrato', 'estado'], name='vehiculos_contrat_ca7728_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['ultimo_mantenimiento_fecha'], name='vehiculos_ultimo__214900_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['proximo_mantenimiento_km'], name='vehiculos_proximo_3e6ae4_idx'),
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='drilling.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='mantenimientovehiculo',
            index=models.Index(fields=['vehiculo', 'fecha_mantenimiento'], name='mantenimien_vehicul_b5e135_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientovehiculo',
            index=models.Index(fields=['tipo_mantenimiento'], name='mantenimien_tipo_ma_616d11_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientovehiculo',
            index=models.Index(fields=['fecha_mantenimiento'], name='mantenimien_fecha_m_0799f6_idx'),
        ),
    ]
