# Generated by Django 5.0.7 on 2025-11-28 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0044_add_vehiculo_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('TRABAJADO', 'Trabajado'), ('DIA_LIBRE', 'Día Libre'), ('DIA_APOYO', 'Día de Apoyo'), ('PERMISO_PATERNIDAD', 'Permiso Paternidad'), ('DESCANSO_MEDICO', 'Descanso Médico'), ('STAND_BY', 'Stand By'), ('SUBSIDIO', 'Subsidio'), ('INDUCCION', 'Inducción'), ('INDUCCION_VIRTUAL', 'Inducción Virtual'), ('RECORRIDO', 'Recorrido'), ('FALTA', 'Falta'), ('PERMISO', 'Permiso'), ('SUSPENSION', 'Suspensión'), ('VACACIONES', 'Vacaciones'), ('LICENCIA_SIN_GOCE', 'Licencia Sin Goce'), ('CESADO', 'Cesado'), ('TRABAJO_CALIENTE', 'Trabajo en Caliente'), ('LICENCIA_FALLECIMIENTO', 'Licencia por Fallecimiento'), ('LICENCIA_CON_GOCE', 'Licencia Con Goce')], default='TRABAJADO', max_length=30, verbose_name='Estado de asistencia')),
                ('observaciones', models.TextField(blank=True, help_text='Detalles adicionales sobre la asistencia', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='drilling.trabajador')),
            ],
            options={
                'verbose_name': 'Asistencia de Trabajador',
                'verbose_name_plural': 'Asistencias de Trabajadores',
                'db_table': 'asistencia_trabajador',
                'ordering': ['-fecha', 'trabajador__apellidos', 'trabajador__nombres'],
                'indexes': [models.Index(fields=['trabajador', 'fecha'], name='asistencia__trabaja_80c988_idx'), models.Index(fields=['fecha'], name='asistencia__fecha_cb75aa_idx'), models.Index(fields=['estado'], name='asistencia__estado_945ce7_idx'), models.Index(fields=['trabajador', 'estado'], name='asistencia__trabaja_f09c1c_idx')],
                'unique_together': {('trabajador', 'fecha')},
            },
        ),
    ]
