# Generated by Django 5.0.7 on 2025-11-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0045_add_asistencia_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciatrabajador',
            name='tipo',
            field=models.CharField(choices=[('PAGABLE', 'Pagable'), ('NO_PAGABLE', 'No Pagable')], default='PAGABLE', help_text='Define si la asistencia es pagable o no pagable', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='asistenciatrabajador',
            index=models.Index(fields=['tipo'], name='asistencia__tipo_ff63e7_idx'),
        ),
    ]
