# Generated by Django 5.0.7 on 2025-12-03 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0046_asistenciatrabajador_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganigramaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio de semana')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin de semana')),
                ('semana_numero', models.PositiveIntegerField(help_text='Semana 1-53', verbose_name='Número de semana del año')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organigramas_semanales', to='drilling.contrato')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organigramas_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organigramas_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organigrama Semanal',
                'verbose_name_plural': 'Organigramas Semanales',
                'db_table': 'organigrama_semanal',
                'ordering': ['-anio', '-semana_numero'],
            },
        ),
        migrations.CreateModel(
            name='GuardiaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardia', models.CharField(choices=[('A', 'Guardia A'), ('B', 'Guardia B'), ('C', 'Guardia C')], max_length=1)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('STAND_BY', 'Stand By'), ('DESCANSO', 'Descanso')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(limit_choices_to={'cargo__nombre__icontains': 'conductor'}, on_delete=django.db.models.deletion.PROTECT, related_name='guardias_conductor', to='drilling.trabajador')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardias_asignadas', to='drilling.vehiculo')),
                ('organigrama_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias_conductores', to='drilling.organigramasemanal')),
            ],
            options={
                'verbose_name': 'Guardia de Conductor',
                'verbose_name_plural': 'Guardias de Conductores',
                'db_table': 'guardia_conductor',
                'ordering': ['guardia', 'conductor__apellidos'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionOrganigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardia', models.CharField(blank=True, choices=[('A', 'Guardia A'), ('B', 'Guardia B'), ('C', 'Guardia C')], max_length=1, null=True)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('STAND_BY', 'Stand By'), ('DESCANSO_MEDICO', 'Descanso Médico'), ('VACACIONES', 'Vacaciones'), ('LICENCIA', 'Licencia')], default='OPERATIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_semanales', to='drilling.maquina')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_organigrama', to='drilling.trabajador')),
                ('organigrama_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='drilling.organigramasemanal')),
            ],
            options={
                'verbose_name': 'Asignación de Organigrama',
                'verbose_name_plural': 'Asignaciones de Organigrama',
                'db_table': 'asignacion_organigrama',
                'ordering': ['trabajador__apellidos', 'trabajador__nombres'],
            },
        ),
        migrations.AddIndex(
            model_name='organigramasemanal',
            index=models.Index(fields=['contrato', 'anio', 'semana_numero'], name='organigrama_contrat_cac73a_idx'),
        ),
        migrations.AddIndex(
            model_name='organigramasemanal',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='organigrama_fecha_i_b8d97c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organigramasemanal',
            unique_together={('contrato', 'anio', 'semana_numero')},
        ),
        migrations.AddIndex(
            model_name='guardiaconductor',
            index=models.Index(fields=['organigrama_semanal', 'guardia'], name='guardia_con_organig_36d72c_idx'),
        ),
        migrations.AddIndex(
            model_name='guardiaconductor',
            index=models.Index(fields=['estado'], name='guardia_con_estado_d77b14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guardiaconductor',
            unique_together={('organigrama_semanal', 'conductor')},
        ),
        migrations.AddIndex(
            model_name='asignacionorganigrama',
            index=models.Index(fields=['organigrama_semanal', 'maquina'], name='asignacion__organig_3d5414_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionorganigrama',
            index=models.Index(fields=['organigrama_semanal', 'guardia'], name='asignacion__organig_62e36d_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionorganigrama',
            index=models.Index(fields=['estado'], name='asignacion__estado_b8ee83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionorganigrama',
            unique_together={('organigrama_semanal', 'trabajador')},
        ),
    ]
