# Generated by Django 5.0.7 on 2025-12-03 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0047_organigrama_semanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('CELULAR', 'Celular'), ('MODEM', 'Módem'), ('IMPRESORA', 'Impresora'), ('DETECTOR_TORMENTAS', 'Detector de Tormentas'), ('ENMICADORA', 'Enmicadora'), ('RADIO', 'Radio'), ('TABLET', 'Tablet'), ('GPS', 'GPS'), ('OTRO', 'Otro')], max_length=30)),
                ('codigo_interno', models.CharField(help_text='Código único de identificación del equipo', max_length=50, unique=True, verbose_name='Código Interno')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie del fabricante', max_length=100, verbose_name='Número de Serie')),
                ('numero_telefono', models.CharField(blank=True, help_text='Para celulares, radios o módems', max_length=20, verbose_name='Número de Teléfono/IMEI')),
                ('operador', models.CharField(blank=True, help_text='Operador de telefonía o servicio', max_length=50, verbose_name='Operador')),
                ('descripcion', models.TextField(blank=True, help_text='Características adicionales del equipo', verbose_name='Descripción')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('fecha_garantia_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Garantía')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio'), ('BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='drilling.contrato')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'ordering': ['tipo', 'codigo_interno'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_devolucion', models.DateField(blank=True, help_text='Fecha en que el trabajador devolvió el equipo', null=True, verbose_name='Fecha de Devolución')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('PERDIDO', 'Perdido/Extraviado'), ('DAÑADO', 'Dañado')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre la asignación, estado del equipo, etc.', verbose_name='Observaciones')),
                ('acta_entrega', models.BooleanField(default=False, help_text='¿Se firmó acta de entrega-recepción?', verbose_name='Acta de Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organigrama_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_equipos', to='drilling.organigramasemanal')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_asignados', to='drilling.trabajador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='drilling.equipo')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo',
                'verbose_name_plural': 'Asignaciones de Equipos',
                'db_table': 'asignacion_equipo',
                'ordering': ['-fecha_asignacion', 'trabajador__apellidos'],
            },
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['contrato', 'tipo'], name='equipos_contrat_fe47df_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado'], name='equipos_estado_c57426_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['codigo_interno'], name='equipos_codigo__fde5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionequipo',
            index=models.Index(fields=['organigrama_semanal', 'trabajador'], name='asignacion__organig_eaa6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionequipo',
            index=models.Index(fields=['equipo', 'estado'], name='asignacion__equipo__f93f83_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionequipo',
            index=models.Index(fields=['fecha_asignacion'], name='asignacion__fecha_a_f2cfd4_idx'),
        ),
    ]
