# Generated by Django 5.0.7 on 2025-12-03 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0048_add_equipo_and_asignacion_equipo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asignacionequipo',
            name='asignacion__organig_eaa6ba_idx',
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='organigrama_semanal',
            field=models.ForeignKey(blank=True, help_text='Opcional: vinculado al organigrama semanal si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_equipos', to='drilling.organigramasemanal'),
        ),
        migrations.AddIndex(
            model_name='asignacionequipo',
            index=models.Index(fields=['trabajador', 'estado'], name='asignacion__trabaja_64f68c_idx'),
        ),
    ]
