# Generated by Django 5.0.7 on 2025-12-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0049_make_organigrama_optional_in_asignacion_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='grupo',
            field=models.CharField(blank=True, choices=[('OPERADORES', 'Operadores'), ('SERVICIOS_GEOLOGICOS', 'Servicios Geológicos'), ('LINEA_MANDO', 'Línea de Mando'), ('PERSONAL_AUXILIAR', 'Personal Auxiliar')], help_text='Se asigna automáticamente según el cargo', max_length=30, verbose_name='Grupo Funcional'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['grupo'], name='trabajadore_grupo_0e5b21_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['contrato', 'grupo'], name='trabajadore_contrat_5cd2d4_idx'),
        ),
    ]
