# Generated by Django 5.0.7 on 2025-12-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0050_add_grupo_to_trabajador'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='abastecimiento',
            index=models.Index(fields=['contrato'], name='abastecimie_contrat_44b3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='abastecimiento',
            index=models.Index(fields=['contrato', 'fecha'], name='abastecimie_contrat_e9cc55_idx'),
        ),
        migrations.AddIndex(
            model_name='abastecimiento',
            index=models.Index(fields=['familia'], name='abastecimie_familia_748035_idx'),
        ),
        migrations.AddIndex(
            model_name='abastecimiento',
            index=models.Index(fields=['-fecha'], name='abastecimie_fecha_2efbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='abastecimiento',
            index=models.Index(fields=['codigo_producto'], name='abastecimie_codigo__28a461_idx'),
        ),
        migrations.AddIndex(
            model_name='abastecimiento',
            index=models.Index(fields=['serie'], name='abastecimie_serie_f47e40_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['is_active'], name='clientes_is_acti_f2228f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['-created_at'], name='clientes_created_82b9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado'], name='contratos_estado_73ef79_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['cliente', 'estado'], name='contratos_cliente_9fbc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['codigo_centro_costo'], name='contratos_codigo__590dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['-created_at'], name='contratos_created_e7aa2a_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['estado'], name='maquinas_estado_af14d4_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['contrato', 'estado'], name='maquinas_contrat_51ef59_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['nombre'], name='maquinas_nombre_bce371_idx'),
        ),
        migrations.AddIndex(
            model_name='sondaje',
            index=models.Index(fields=['estado'], name='sondajes_estado_953abe_idx'),
        ),
        migrations.AddIndex(
            model_name='sondaje',
            index=models.Index(fields=['contrato', 'estado'], name='sondajes_contrat_6c8283_idx'),
        ),
        migrations.AddIndex(
            model_name='sondaje',
            index=models.Index(fields=['fecha_inicio'], name='sondajes_fecha_i_6bafa3_idx'),
        ),
        migrations.AddIndex(
            model_name='sondaje',
            index=models.Index(fields=['-fecha_inicio'], name='sondajes_fecha_i_57936c_idx'),
        ),
        migrations.AddIndex(
            model_name='sondaje',
            index=models.Index(fields=['fecha_fin'], name='sondajes_fecha_f_0746ed_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoactividad',
            index=models.Index(fields=['tipo_actividad'], name='tipos_activ_tipo_ac_4a9ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoactividad',
            index=models.Index(fields=['es_cobrable'], name='tipos_activ_es_cobr_603a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoactividad',
            index=models.Index(fields=['tipo_actividad', 'es_cobrable'], name='tipos_activ_tipo_ac_f4328c_idx'),
        ),
        migrations.AddIndex(
            model_name='turnoavance',
            index=models.Index(fields=['turno'], name='turno_avanc_turno_i_5f13c5_idx'),
        ),
        migrations.AddIndex(
            model_name='turnoavance',
            index=models.Index(fields=['-created_at'], name='turno_avanc_created_33d56a_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocomplemento',
            index=models.Index(fields=['turno'], name='turno_compl_turno_i_da67a5_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocomplemento',
            index=models.Index(fields=['sondaje'], name='turno_compl_sondaje_75c2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocomplemento',
            index=models.Index(fields=['tipo_complemento'], name='turno_compl_tipo_co_b6b3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocomplemento',
            index=models.Index(fields=['codigo_serie'], name='turno_compl_codigo__4ed1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosondaje',
            index=models.Index(fields=['turno'], name='turno_sonda_turno_i_01d4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosondaje',
            index=models.Index(fields=['sondaje'], name='turno_sonda_sondaje_976ade_idx'),
        ),
        migrations.AddIndex(
            model_name='turnotrabajador',
            index=models.Index(fields=['turno'], name='turno_traba_turno_i_80fca5_idx'),
        ),
        migrations.AddIndex(
            model_name='turnotrabajador',
            index=models.Index(fields=['trabajador'], name='turno_traba_trabaja_b62e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='turnotrabajador',
            index=models.Index(fields=['funcion'], name='turno_traba_funcion_69cb75_idx'),
        ),
    ]
