# Generated by Django 5.0.7 on 2025-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0051_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador de Contrato'), ('LOGISTICO', 'Logístico'), ('RESIDENTE', 'Residente'), ('CONTROL_PROYECTOS', 'Control de Proyectos'), ('GERENCIA', 'Gerencia')], default='ADMINISTRADOR', help_text='Define los permisos y accesos del usuario', max_length=30, verbose_name='Rol del usuario'),
        ),
    ]
