# Generated by Django 5.0.7 on 2025-12-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0052_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(db_index=True, help_text='Código de serie único de la broca', max_length=100, unique=True, verbose_name='Serie')),
                ('metraje_acumulado', models.DecimalField(decimal_places=2, default=0, help_text='Total de metros perforados con esta broca', max_digits=10, verbose_name='Metraje Acumulado (m)')),
                ('numero_usos', models.PositiveIntegerField(default=0, help_text='Cantidad de turnos donde se usó esta broca', verbose_name='Número de Usos')),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('EN_USO', 'En Uso'), ('DESGASTADA', 'Desgastada'), ('QUEMADA', 'Quemada'), ('FUERA_SERVICIO', 'Fuera de Servicio'), ('PERDIDA', 'Perdida')], db_index=True, default='NUEVA', max_length=20, verbose_name='Estado')),
                ('fecha_primer_uso', models.DateField(blank=True, null=True, verbose_name='Fecha Primer Uso')),
                ('fecha_ultimo_uso', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha Último Uso')),
                ('fecha_baja', models.DateField(blank=True, help_text='Fecha en que se dio de baja la broca (quemada, perdida, etc.)', null=True, verbose_name='Fecha de Baja')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre el estado de la broca, desgaste observado, etc.', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato_actual', models.ForeignKey(help_text='Último contrato donde se usó la broca', on_delete=django.db.models.deletion.PROTECT, related_name='brocas_historial', to='drilling.contrato', verbose_name='Contrato Actual')),
                ('tipo_complemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='drilling.tipocomplemento', verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name': 'Historial de Broca',
                'verbose_name_plural': 'Historiales de Brocas',
                'db_table': 'historial_broca',
                'ordering': ['-fecha_ultimo_uso', '-metraje_acumulado'],
                'indexes': [models.Index(fields=['serie'], name='historial_b_serie_af2114_idx'), models.Index(fields=['estado'], name='historial_b_estado_8dfd10_idx'), models.Index(fields=['contrato_actual', 'estado'], name='historial_b_contrat_5920a5_idx'), models.Index(fields=['-metraje_acumulado'], name='historial_b_metraje_49cafc_idx'), models.Index(fields=['-fecha_ultimo_uso'], name='historial_b_fecha_u_0fec7c_idx')],
            },
        ),
    ]
