# Generated by Django 5.2.6 on 2025-12-27 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0053_historial_broca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_stock_critico', models.PositiveIntegerField(default=5, help_text='Se genera alerta crítica si quedan menos de estos días', verbose_name='Días para Stock Crítico')),
                ('dias_stock_bajo', models.PositiveIntegerField(default=15, help_text='Se genera alerta de stock bajo si quedan menos de estos días', verbose_name='Días para Stock Bajo')),
                ('dias_stock_alerta', models.PositiveIntegerField(default=30, help_text='Se genera pre-alerta si quedan menos de estos días', verbose_name='Días para Pre-alerta')),
                ('dias_sin_rotacion', models.PositiveIntegerField(default=30, help_text='Alertar si un artículo no ha tenido movimiento en estos días', verbose_name='Días sin Rotación')),
                ('pct_consumo_anormal', models.PositiveIntegerField(default=150, help_text='Alertar si el consumo supera este % del promedio', verbose_name='% Consumo Anormal')),
                ('enviar_email', models.BooleanField(default=True, help_text='Enviar notificación por email cuando se genere una alerta crítica', verbose_name='Enviar Email')),
                ('emails_notificacion', models.TextField(blank=True, help_text='Lista de emails separados por coma para notificaciones', verbose_name='Emails de Notificación')),
                ('alertar_stock_bajo', models.BooleanField(default=True, verbose_name='Alertar Stock Bajo')),
                ('alertar_agotado', models.BooleanField(default=True, verbose_name='Alertar Agotado')),
                ('alertar_sin_rotacion', models.BooleanField(default=True, verbose_name='Alertar Sin Rotación')),
                ('alertar_consumo_anormal', models.BooleanField(default=True, verbose_name='Alertar Consumo Anormal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_alertas_stock', to='drilling.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Configuración de Alertas de Stock',
                'verbose_name_plural': 'Configuraciones de Alertas de Stock',
                'db_table': 'configuracion_alerta_stock',
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(max_length=50, verbose_name='Código Artículo')),
                ('descripcion_articulo', models.CharField(max_length=255, verbose_name='Descripción Artículo')),
                ('familia', models.CharField(choices=[('PDD', 'Productos Diamantados'), ('ADIT', 'Aditivos')], max_length=10, verbose_name='Familia')),
                ('tipo_alerta', models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('STOCK_CRITICO', 'Stock Crítico'), ('AGOTADO', 'Agotado'), ('SIN_ROTACION', 'Sin Rotación'), ('CONSUMO_ANORMAL', 'Consumo Anormal'), ('REPOSICION_URGENTE', 'Reposición Urgente')], max_length=20, verbose_name='Tipo de Alerta')),
                ('prioridad', models.PositiveSmallIntegerField(choices=[(1, 'Crítica'), (2, 'Alta'), (3, 'Media'), (4, 'Baja')], default=3, verbose_name='Prioridad')),
                ('mensaje', models.TextField(verbose_name='Mensaje de Alerta')),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Actual')),
                ('consumo_diario_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumo Diario Promedio')),
                ('dias_stock_restante', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Días de Stock Restante')),
                ('umbral_configurado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor del umbral que disparó la alerta', max_digits=10, null=True, verbose_name='Umbral Configurado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('resuelta', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('nota_resolucion', models.TextField(blank=True, verbose_name='Nota de Resolución')),
                ('hash_alerta', models.CharField(help_text='Para evitar alertas duplicadas del mismo evento', max_length=64, unique=True, verbose_name='Hash Único')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_stock', to='drilling.contrato', verbose_name='Contrato')),
                ('leida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_stock_leidas', to=settings.AUTH_USER_MODEL, verbose_name='Leída por')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_stock_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'db_table': 'alerta_stock',
                'ordering': ['prioridad', '-fecha_creacion'],
                'indexes': [models.Index(fields=['contrato', 'resuelta'], name='alerta_stoc_contrat_b68344_idx'), models.Index(fields=['contrato', 'tipo_alerta'], name='alerta_stoc_contrat_4e7b2c_idx'), models.Index(fields=['prioridad', '-fecha_creacion'], name='alerta_stoc_priorid_ac2c82_idx'), models.Index(fields=['codigo_articulo'], name='alerta_stoc_codigo__89b3f7_idx'), models.Index(fields=['hash_alerta'], name='alerta_stoc_hash_al_23a609_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sync', models.DateTimeField(auto_now_add=True, help_text='Momento exacto en que se tomó la foto del stock', verbose_name='Fecha de Sincronización')),
                ('familia', models.CharField(choices=[('PDD', 'Productos Diamantados'), ('ADIT', 'Aditivos')], max_length=10, verbose_name='Familia de Producto')),
                ('codigo_articulo', models.CharField(help_text='Código del artículo en el sistema Vilbragroup', max_length=50, verbose_name='Código Artículo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('stock_cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad en Stock')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación en Almacén')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Unitario')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True, verbose_name='Valor Total')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='drilling.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Snapshot de Stock',
                'verbose_name_plural': 'Snapshots de Stock',
                'db_table': 'stock_snapshot',
                'ordering': ['-fecha_sync', 'familia', 'codigo_articulo'],
                'indexes': [models.Index(fields=['contrato', 'fecha_sync'], name='stock_snaps_contrat_558f00_idx'), models.Index(fields=['contrato', 'familia'], name='stock_snaps_contrat_8c13c1_idx'), models.Index(fields=['codigo_articulo'], name='stock_snaps_codigo__a707eb_idx'), models.Index(fields=['contrato', 'codigo_articulo', '-fecha_sync'], name='stock_snaps_contrat_54d4a2_idx'), models.Index(fields=['-fecha_sync'], name='stock_snaps_fecha_s_eab727_idx')],
            },
        ),
    ]
