# Generated by Django 5.2.6 on 2026-01-03 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0054_stock_snapshots_alertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciatrabajador',
            name='cargo_snapshot',
            field=models.CharField(blank=True, help_text='Cargo del trabajador al momento del registro', max_length=200, null=True, verbose_name='Cargo (Histórico)'),
        ),
        migrations.AddField(
            model_name='asistenciatrabajador',
            name='guardia_snapshot',
            field=models.CharField(blank=True, help_text='Guardia asignada al momento del registro', max_length=1, null=True, verbose_name='Guardia (Histórico)'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_inicio_ciclo',
            field=models.DateField(blank=True, help_text='Fecha de inicio del ciclo actual (Día 1 de trabajo)', null=True, verbose_name='Inicio de Ciclo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='regimen_laboral',
            field=models.CharField(choices=[('14x7', '14 Días Trabajo x 7 Días Descanso'), ('20x10', '20 Días Trabajo x 10 Días Descanso'), ('28x14', '28 Días Trabajo x 14 Días Descanso'), ('5x2', '5 Días Trabajo x 2 Días Descanso'), ('6x1', '6 Días Trabajo x 1 Día Descanso')], default='14x7', max_length=10, verbose_name='Régimen Laboral'),
        ),
        migrations.CreateModel(
            name='HistorialLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('guardia', models.CharField(blank=True, choices=[('A', 'Guardia A'), ('B', 'Guardia B'), ('C', 'Guardia C')], max_length=1, null=True, verbose_name='Guardia')),
                ('regimen', models.CharField(blank=True, choices=[('14x7', '14 Días Trabajo x 7 Días Descanso'), ('20x10', '20 Días Trabajo x 10 Días Descanso'), ('28x14', '28 Días Trabajo x 14 Días Descanso'), ('5x2', '5 Días Trabajo x 2 Días Descanso'), ('6x1', '6 Días Trabajo x 1 Día Descanso')], max_length=10, null=True, verbose_name='Régimen')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drilling.cargo', verbose_name='Cargo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_laboral', to='drilling.trabajador')),
            ],
            options={
                'verbose_name': 'Historial Laboral',
                'verbose_name_plural': 'Historiales Laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
