# Generated by Django 5.2.6 on 2026-01-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0055_asistenciatrabajador_cargo_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='tipo_trabajo',
            field=models.CharField(choices=[('SUBTERRANEA', 'Interior Mina'), ('SUPERFICIAL', 'Superficial')], default='SUBTERRANEA', max_length=20, verbose_name='Tipo de Trabajo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_trabajo',
            field=models.CharField(choices=[('SUBTERRANEA', 'Interior Mina'), ('SUPERFICIAL', 'Superficial')], default='SUBTERRANEA', max_length=20, verbose_name='Tipo de Trabajo'),
        ),
    ]
