# Generated by Django 5.2.6 on 2026-01-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0056_maquina_tipo_trabajo_trabajador_tipo_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='grupo',
            field=models.CharField(blank=True, choices=[('OPERADORES_INTERIOR_MINA', 'Operadores Interior Mina'), ('OPERADORES_SUPERFICIE', 'Operadores Superficie'), ('SERVICIOS_GEOLOGICOS_INTERIOR_MINA', 'Servicios Geológicos Interior Mina'), ('SERVICIOS_GEOLOGICOS_SUPERFICIE', 'Servicios Geológicos Superficie'), ('CONDUCTORES_INTERIOR_MINA', 'Conductores Interior Mina'), ('CONDUCTORES_SUPERFICIE', 'Conductores Superficie'), ('LINEA_MANDO', 'Línea de Mando'), ('OPERADORES', 'Operadores (Legacy)'), ('SERVICIOS_GEOLOGICOS', 'Servicios Geológicos (Legacy)'), ('CONDUCTORES', 'Conductores (Legacy)')], help_text='Se asigna automáticamente según el cargo y zona de trabajo', max_length=50, verbose_name='Grupo Funcional'),
        ),
    ]
