# Generated by Django 5.2.6 on 2026-01-19 02:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0058_add_comentarios_litologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador de Contrato'), ('LOGISTICO', 'Logístico'), ('RESIDENTE', 'Residente'), ('CONTROL_PROYECTOS', 'Control de Proyectos'), ('GERENCIA', 'Gerencia'), ('GERENTE_GENERAL', 'Gerente General'), ('HEADCOUNT', 'Gestión de Personal y Headcount')], default='ADMINISTRADOR', help_text='Define los permisos y accesos del usuario', max_length=30, verbose_name='Rol del usuario'),
        ),
        migrations.CreateModel(
            name='HeadCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.PositiveIntegerField(default=1, help_text='Número de trabajadores requeridos para este cargo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Requerida')),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios adicionales sobre este requerimiento', verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este requerimiento está vigente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headcounts', to='drilling.cargo', verbose_name='Cargo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headcounts', to='drilling.contrato', verbose_name='Contrato')),
                ('maquina', models.ForeignKey(blank=True, help_text='Máquina a la que se asignará el personal (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headcounts', to='drilling.maquina', verbose_name='Máquina Asignada')),
            ],
            options={
                'verbose_name': 'Headcount',
                'verbose_name_plural': 'Headcounts',
                'db_table': 'headcount',
                'ordering': ['contrato', 'cargo__nombre'],
                'indexes': [models.Index(fields=['contrato', 'activo'], name='headcount_contrat_201d4e_idx'), models.Index(fields=['cargo'], name='headcount_cargo_i_ebf1c1_idx'), models.Index(fields=['maquina'], name='headcount_maquina_53d173_idx'), models.Index(fields=['-created_at'], name='headcount_created_04628d_idx')],
                'unique_together': {('contrato', 'cargo', 'maquina')},
            },
        ),
    ]
