# Generated by Django 5.2.6 on 2026-01-24 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0059_agregar_rol_gerente_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('TRABAJO', 'Trabajo'), ('DESCANSO', 'Descanso'), ('FALTA', 'Falta'), ('DM', 'Descanso Médico'), ('VACACIONES', 'Vacaciones'), ('PERMISO', 'Permiso'), ('SUSPENSION', 'Suspensión'), ('LICENCIA', 'Licencia'), ('INDUCCION', 'Inducción'), ('STAND_BY', 'Stand By'), ('DIA_APOYO', 'Día de Apoyo')], db_index=True, default='TRABAJO', max_length=20, verbose_name='Estado')),
                ('guardia_snapshot', models.CharField(blank=True, help_text='Guardia del trabajador al momento del registro (A/B/C)', max_length=1, null=True, verbose_name='Guardia Asignada (Snapshot)')),
                ('es_proyeccion', models.BooleanField(db_index=True, default=False, help_text='True = proyección automática | False = corrección manual', verbose_name='Es Proyección')),
                ('observaciones', models.TextField(blank=True, help_text='Detalles adicionales sobre la asistencia', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_diarias', to='drilling.trabajador', verbose_name='Trabajador')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas_v2', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Asistencia Diaria',
                'verbose_name_plural': 'Asistencias Diarias',
                'db_table': 'asistencia_diaria',
                'ordering': ['-fecha', 'empleado__apellidos', 'empleado__nombres'],
            },
        ),
        migrations.CreateModel(
            name='CierreMensualTareo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(help_text='1-12', verbose_name='Mes')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_REVISION', 'En Revisión'), ('CERRADO', 'Cerrado'), ('REABIERTO', 'Reabierto')], default='ABIERTO', max_length=15, verbose_name='Estado')),
                ('total_trabajadores', models.IntegerField(default=0, verbose_name='Total Trabajadores')),
                ('total_dias_trabajo', models.IntegerField(default=0, verbose_name='Total Días Trabajo')),
                ('total_dias_descanso', models.IntegerField(default=0, verbose_name='Total Días Descanso')),
                ('total_faltas', models.IntegerField(default=0, verbose_name='Total Faltas')),
                ('total_vacaciones', models.IntegerField(default=0, verbose_name='Total Vacaciones')),
                ('total_permisos', models.IntegerField(default=0, verbose_name='Total Permisos')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('fecha_reapertura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reapertura')),
                ('motivo_reapertura', models.TextField(blank=True, verbose_name='Motivo de Reapertura')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cerrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_tareo', to='drilling.contrato', verbose_name='Contrato')),
                ('reabierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaperturas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Reabierto por')),
            ],
            options={
                'verbose_name': 'Cierre Mensual de Tareo',
                'verbose_name_plural': 'Cierres Mensuales de Tareo',
                'db_table': 'cierre_mensual_tareo',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambioAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('es_proyeccion_anterior', models.BooleanField(verbose_name='Era Proyección')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado Nuevo')),
                ('es_proyeccion_nuevo', models.BooleanField(verbose_name='Es Proyección')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo del Cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('mes_cerrado', models.BooleanField(default=False, help_text='Indica si el cambio se hizo en un mes cerrado (requiere justificación)', verbose_name='Mes estaba cerrado')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='drilling.asistenciadiaria', verbose_name='Asistencia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_asistencia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó')),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Asistencia',
                'verbose_name_plural': 'Historial de Cambios de Asistencia',
                'db_table': 'historial_cambio_asistencia',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='asistenciadiaria',
            index=models.Index(fields=['empleado', 'fecha'], name='idx_empleado_fecha'),
        ),
        migrations.AddIndex(
            model_name='asistenciadiaria',
            index=models.Index(fields=['fecha', 'estado'], name='idx_fecha_estado'),
        ),
        migrations.AddIndex(
            model_name='asistenciadiaria',
            index=models.Index(fields=['es_proyeccion', 'fecha'], name='idx_proyeccion_fecha'),
        ),
        migrations.AddIndex(
            model_name='asistenciadiaria',
            index=models.Index(fields=['registrado_por', '-created_at'], name='idx_auditoria'),
        ),
        migrations.AddConstraint(
            model_name='asistenciadiaria',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha'), name='unique_empleado_fecha'),
        ),
        migrations.AddIndex(
            model_name='cierremensualtareo',
            index=models.Index(fields=['contrato', '-anio', '-mes'], name='idx_cierre_contrato_periodo'),
        ),
        migrations.AddIndex(
            model_name='cierremensualtareo',
            index=models.Index(fields=['estado', 'fecha_cierre'], name='idx_cierre_estado'),
        ),
        migrations.AddConstraint(
            model_name='cierremensualtareo',
            constraint=models.UniqueConstraint(fields=('contrato', 'anio', 'mes'), name='unique_cierre_contrato_mes'),
        ),
        migrations.AddIndex(
            model_name='historialcambioasistencia',
            index=models.Index(fields=['asistencia', '-fecha_cambio'], name='idx_hist_asistencia'),
        ),
        migrations.AddIndex(
            model_name='historialcambioasistencia',
            index=models.Index(fields=['usuario', '-fecha_cambio'], name='idx_hist_usuario'),
        ),
        migrations.AddIndex(
            model_name='historialcambioasistencia',
            index=models.Index(fields=['-fecha_cambio'], name='idx_hist_fecha'),
        ),
    ]
