# Generated by Django 5.2.6 on 2026-01-24 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0060_asistenciadiaria_cierremensualtareo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadiaria',
            name='maquina_snapshot',
            field=models.ForeignKey(blank=True, help_text='Máquina específica asignada para este día', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_diarias', to='drilling.maquina', verbose_name='Máquina Asignada'),
        ),
    ]
