# Generated by Django 5.2.6 on 2026-02-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0061_add_maquina_snapshot_to_asistencia_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='es_standby',
            field=models.BooleanField(default=False, help_text='Marca este trabajador como personal de reserva para cubrir ausencias. No se asigna a guardia fija.', verbose_name='Personal STANDBY'),
        ),
    ]
