# Generated by Django 5.2.6 on 2026-02-06 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0062_add_es_standby_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbastecimientoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha de Abastecimiento')),
                ('centro_costo', models.CharField(db_index=True, max_length=50, verbose_name='Centro de Costo')),
                ('documento', models.CharField(db_index=True, help_text='Número de documento del abastecimiento', max_length=100, verbose_name='Número de Documento')),
                ('documento_referencia', models.CharField(blank=True, help_text='Documento de referencia asociado', max_length=100, verbose_name='Documento de Referencia')),
                ('codigo', models.CharField(db_index=True, max_length=100, verbose_name='Código de Artículo')),
                ('serie', models.CharField(blank=True, db_index=True, help_text='Serie individual del artículo (especialmente importante para brocas)', max_length=100, null=True, verbose_name='Serie')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('codigo_movimiento', models.CharField(db_index=True, max_length=50, verbose_name='Código de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unidad', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('familia', models.CharField(db_index=True, help_text='Familia del artículo (PDD, ADIT, etc.)', max_length=20, verbose_name='Familia')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Total')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se sincronizó este registro desde la API', verbose_name='Fecha de Sincronización')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('contrato', models.ForeignKey(help_text='Contrato asociado al centro de costo', on_delete=django.db.models.deletion.PROTECT, related_name='abastecimientos_api', to='drilling.contrato', verbose_name='Contrato')),
                ('historial_broca', models.ForeignKey(blank=True, help_text='Referencia al historial de la broca (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimientos', to='drilling.historialbroca', verbose_name='Historial de Broca')),
            ],
            options={
                'verbose_name': 'Abastecimiento de Artículo',
                'verbose_name_plural': 'Abastecimientos de Artículos',
                'db_table': 'abastecimiento_articulo',
                'ordering': ['-fecha', '-fecha_sincronizacion'],
                'indexes': [models.Index(fields=['fecha', 'centro_costo'], name='abastecimie_fecha_9dd229_idx'), models.Index(fields=['familia', 'codigo'], name='abastecimie_familia_ab906a_idx'), models.Index(fields=['serie'], name='idx_abastec_serie'), models.Index(fields=['contrato', 'fecha'], name='abastecimie_contrat_e0eb9a_idx')],
                'unique_together': {('documento', 'codigo', 'serie')},
            },
        ),
    ]
