# Generated by Django 5.0.7 on 2026-02-06 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0063_abastecimiento_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha de Consumo')),
                ('centro_costo', models.CharField(db_index=True, max_length=50, verbose_name='Centro de Costo')),
                ('documento', models.CharField(db_index=True, help_text='Número de documento de salida/vale', max_length=100, verbose_name='Número de Documento')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, verbose_name='Documento de Referencia')),
                ('codigo', models.CharField(db_index=True, max_length=100, verbose_name='Código de Artículo')),
                ('serie', models.CharField(blank=True, db_index=True, help_text='Serie individual del artículo (si aplica)', max_length=100, null=True, verbose_name='Serie')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('codigo_movimiento', models.CharField(db_index=True, max_length=50, verbose_name='Código de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unidad', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('familia', models.CharField(db_index=True, help_text='Familia del artículo', max_length=20, verbose_name='Familia')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Sincronización')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('contrato', models.ForeignKey(help_text='Contrato asociado al centro de costo', on_delete=django.db.models.deletion.PROTECT, related_name='consumos_api', to='drilling.contrato', verbose_name='Contrato')),
                ('historial_broca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='drilling.historialbroca', verbose_name='Historial de Broca')),
            ],
            options={
                'verbose_name': 'Consumo de Artículo',
                'verbose_name_plural': 'Consumos de Artículos',
                'db_table': 'consumo_articulo',
                'ordering': ['-fecha', '-fecha_sincronizacion'],
                'indexes': [models.Index(fields=['fecha', 'centro_costo'], name='consumo_art_fecha_ab16bd_idx'), models.Index(fields=['familia', 'codigo'], name='consumo_art_familia_ad525b_idx'), models.Index(fields=['serie'], name='idx_consumo_serie'), models.Index(fields=['contrato', 'fecha'], name='consumo_art_contrat_790d53_idx')],
                'unique_together': {('documento', 'codigo', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='InventarioAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, verbose_name='Código de Artículo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('familia', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Familia')),
                ('unidad_medida', models.CharField(blank=True, max_length=20, verbose_name='Unidad de Medida')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock Actual')),
                ('validez_stock', models.CharField(choices=[('VALIDO', 'Válido'), ('BAJO', 'Stock Bajo'), ('CRITICO', 'Crítico'), ('NEGATIVO', 'Negativo')], default='VALIDO', max_length=20, verbose_name='Estado de Stock')),
                ('ultima_sincronizacion', models.DateTimeField(auto_now=True, verbose_name='Último Recálculo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_almacen', to='drilling.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Inventario de Almacén',
                'verbose_name_plural': 'Inventario de Almacén',
                'db_table': 'inventario_almacen',
                'indexes': [models.Index(fields=['contrato', 'familia'], name='inventario__contrat_d0a1c3_idx'), models.Index(fields=['cantidad_actual'], name='inventario__cantida_533fa7_idx')],
                'unique_together': {('contrato', 'codigo')},
            },
        ),
    ]
