# Generated by Django 5.0.7 on 2026-02-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0064_consumoarticulo_inventarioalmacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='codigo_almacen',
            field=models.CharField(blank=True, help_text='Código utilizado en la API de Consumos (ej: 15)', max_length=50, null=True, verbose_name='Código Almacén API'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='codigo_centro_costo',
            field=models.CharField(blank=True, help_text='Código del centro de costo (ej: 000035)', max_length=50, null=True, verbose_name='Código Centro de Costo'),
        ),
    ]
