# Generated by Django 5.0.7 on 2026-02-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0065_contrato_codigo_almacen_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumoarticulo',
            unique_together={('centro_costo', 'fecha', 'documento', 'codigo', 'serie')},
        ),
    ]
