# Generated by Django 5.0.7 on 2026-02-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0066_alter_consumoarticulo_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadorAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('nombres', models.CharField(blank=True, max_length=200)),
                ('apepat', models.CharField(blank=True, max_length=100, verbose_name='Apellido Paterno')),
                ('apemat', models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno')),
                ('cargo_nombre', models.CharField(blank=True, max_length=200, verbose_name='Cargo (Texto API)')),
                ('centro_costo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Centro Costo (API)')),
                ('contrato_nombre', models.CharField(blank=True, max_length=200, verbose_name='Contrato (Texto API)')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha Contratación')),
                ('estado_api', models.CharField(blank=True, max_length=50, verbose_name='Estado API')),
                ('guardia_asignada', models.CharField(blank=True, choices=[('A', 'Guardia A'), ('B', 'Guardia B'), ('C', 'Guardia C')], max_length=1, null=True)),
                ('es_standby', models.BooleanField(default=False)),
                ('regimen_laboral', models.CharField(choices=[('14x7', '14 Días Trabajo x 7 Días Descanso'), ('20x10', '20 Días Trabajo x 10 Días Descanso'), ('28x14', '28 Días Trabajo x 14 Días Descanso'), ('5x2', '5 Días Trabajo x 2 Días Descanso'), ('6x1', '6 Días Trabajo x 1 Día Descanso')], default='14x7', max_length=10)),
                ('fecha_inicio_ciclo', models.DateField(blank=True, null=True)),
                ('tipo_trabajo', models.CharField(choices=[('SUBTERRANEA', 'Interior Mina'), ('SUPERFICIAL', 'Superficial')], default='SUBTERRANEA', max_length=20)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subestado', models.CharField(choices=[('EN_OPERACION', 'En Operación'), ('DESCANSO_MEDICO', 'Descanso Médico'), ('DIAS_LIBRES', 'Días Libres'), ('FALTA', 'Falta')], default='EN_OPERACION', max_length=30)),
                ('fotocheck_fecha_emision', models.DateField(blank=True, null=True)),
                ('synced', models.BooleanField(default=False, verbose_name='Sincronizado')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='Última Sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_api', to='drilling.cargo')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_api', to='drilling.contrato')),
                ('maquina_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drilling.maquina')),
                ('vehiculo_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drilling.vehiculo')),
            ],
            options={
                'verbose_name': 'Trabajador API (Nuevo Modelo)',
                'verbose_name_plural': 'Trabajadores API (Nuevo Modelo)',
                'db_table': 'trabajadores_api_staging',
                'ordering': ['-created_at'],
            },
        ),
    ]
