# Generated by Django 5.0.7 on 2026-02-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0067_trabajadorapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='cargo_superior',
        ),
        migrations.AlterField(
            model_name='historiallaboral',
            name='cargo',
            field=models.CharField(max_length=200, verbose_name='Cargo'),
        ),
        migrations.RemoveField(
            model_name='trabajadorapi',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='cargo',
            field=models.CharField(max_length=200, verbose_name='Cargo'),
        ),
        migrations.RemoveField(
            model_name='trabajadorapi',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='trabajadorapi',
            name='maquina_asignada',
        ),
        migrations.RemoveField(
            model_name='trabajadorapi',
            name='vehiculo_asignado',
        ),
        migrations.AlterModelOptions(
            name='asignacionequipo',
            options={'ordering': ['-fecha_asignacion', 'trabajador__apepat'], 'verbose_name': 'Asignación de Equipo', 'verbose_name_plural': 'Asignaciones de Equipos'},
        ),
        migrations.AlterModelOptions(
            name='asignacionorganigrama',
            options={'ordering': ['trabajador__apepat', 'trabajador__nombres'], 'verbose_name': 'Asignación de Organigrama', 'verbose_name_plural': 'Asignaciones de Organigrama'},
        ),
        migrations.AlterModelOptions(
            name='asistenciadiaria',
            options={'ordering': ['-fecha', 'empleado__apepat', 'empleado__nombres'], 'verbose_name': 'Asistencia Diaria', 'verbose_name_plural': 'Asistencias Diarias'},
        ),
        migrations.AlterModelOptions(
            name='asistenciatrabajador',
            options={'ordering': ['-fecha', 'trabajador__apepat', 'trabajador__nombres'], 'verbose_name': 'Asistencia de Trabajador', 'verbose_name_plural': 'Asistencias de Trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='guardiaconductor',
            options={'ordering': ['guardia', 'conductor__apepat'], 'verbose_name': 'Guardia de Conductor', 'verbose_name_plural': 'Guardias de Conductores'},
        ),
        migrations.AlterModelOptions(
            name='headcount',
            options={'ordering': ['contrato', 'cargo'], 'verbose_name': 'Headcount', 'verbose_name_plural': 'Headcounts'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='turnohoraextra',
            options={'ordering': ['-turno__fecha', 'trabajador__apepat'], 'verbose_name': 'Hora Extra de Turno', 'verbose_name_plural': 'Horas Extras de Turnos'},
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='trabajadore_estado_1a4a8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='trabajadore_subesta_0fde56_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='trabajadore_contrat_8d72ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='trabajadore_fotoche_5f841d_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='trabajadore_emo_fec_b97e5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='trabajadore_emo_pro_e2ca0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='trabajadore_area_c043b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='trabajadore_grupo_0e5b21_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='trabajadore_contrat_5cd2d4_idx',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='updated_at',
            new_name='last_synced_at',
        ),
        migrations.RenameIndex(
            model_name='headcount',
            new_name='headcount_cargo_69f577_idx',
            old_name='headcount_cargo_i_ebf1c1_idx',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='emo_estado',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='emo_fecha_realizado',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='emo_fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='emo_programacion',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='fotocheck_fecha_caducidad',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='grupo',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='apemat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='apepat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Centro Costo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='contrato_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contrato (Texto)'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estado_api',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado API'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Contratación'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='drilling.contrato'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='es_standby',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='estado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_inicio_ciclo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fotocheck_fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='guardia_asignada',
            field=models.CharField(blank=True, choices=[('A', 'Guardia A'), ('B', 'Guardia B'), ('C', 'Guardia C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='maquina_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_asignados', to='drilling.maquina'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='regimen_laboral',
            field=models.CharField(choices=[('14x7', '14 Días Trabajo x 7 Días Descanso'), ('20x10', '20 Días Trabajo x 10 Días Descanso'), ('28x14', '28 Días Trabajo x 14 Días Descanso'), ('5x2', '5 Días Trabajo x 2 Días Descanso'), ('6x1', '6 Días Trabajo x 1 Día Descanso')], default='14x7', max_length=10),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='subestado',
            field=models.CharField(choices=[('EN_OPERACION', 'En Operación'), ('DESCANSO_MEDICO', 'Descanso Médico'), ('DIAS_LIBRES', 'Días Libres'), ('FALTA', 'Falta')], default='EN_OPERACION', max_length=30),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='tipo_trabajo',
            field=models.CharField(choices=[('SUBTERRANEA', 'Interior Mina'), ('SUPERFICIAL', 'Superficial')], default='SUBTERRANEA', max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='vehiculo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores_asignados', to='drilling.vehiculo'),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='TrabajadorAPI',
        ),
    ]
