# Generated by Django 5.0.7 on 2026-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0068_remove_cargo_cargo_superior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='grupo',
            field=models.CharField(blank=True, choices=[('OPERADORES', 'Operadores'), ('SERVICIOS_GEOLOGICOS', 'Servicios Geológicos'), ('CONDUCTORES', 'Conductores'), ('LINEA_MANDO', 'Línea de Mando')], help_text='Asignado automáticamente según el cargo', max_length=30, null=True, verbose_name='Grupo Funcional'),
        ),
    ]
