# Generated by Django 5.0.7 on 2026-02-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0069_add_grupo_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('DDH', 'Perforación Diamantina (DDH)'), ('SGEOL', 'Servicios Geológicos (SGEOL)'), ('WDTH', 'Wireline / Downhole (WDTH)'), ('VCR', 'VCR / Raise Boring (VCR)'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo de Servicio')),
                ('codigo_centro_costo', models.CharField(help_text='Ej: 000402', max_length=50, verbose_name='Código Centro de Costo')),
                ('codigo_almacen', models.CharField(blank=True, help_text='Para consumos (ej: 16)', max_length=50, null=True, verbose_name='Código Almacén API')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción adicional (opcional)', max_length=200, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='drilling.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Servicio de Contrato',
                'verbose_name_plural': 'Servicios de Contrato',
                'db_table': 'contrato_servicios',
                'ordering': ['tipo_servicio'],
                'unique_together': {('contrato', 'codigo_centro_costo')},
            },
        ),
    ]
