# Generated by Django 5.0.7 on 2026-02-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0070_add_contrato_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('DDH', 'Perforación Diamantina (DDH)'), ('SGEOL', 'Servicios Geológicos (SGEOL)'), ('WDTH', 'Wireline / Downhole (WDTH)'), ('VCR', 'Vacuum Core Recovery (VCR)'), ('OTRO', 'Otro')], help_text='DDH, SGEOL, WDTH o VCR — calculado automáticamente desde el cargo', max_length=10, null=True, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR_GENERAL', 'Administrador General del Sistema'), ('ADMINISTRADOR', 'Administrador de Contrato'), ('LOGISTICO', 'Logístico'), ('RESIDENTE', 'Residente'), ('CONTROL_PROYECTOS', 'Control de Proyectos'), ('GERENCIA', 'Gerencia'), ('GERENTE_GENERAL', 'Gerente General'), ('HEADCOUNT', 'Gestión de Personal y Headcount')], default='ADMINISTRADOR', help_text='Define los permisos y accesos del usuario', max_length=30, verbose_name='Rol del usuario'),
        ),
    ]
