# Generated by Django 5.0.7 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0072_add_fecha_inicio_labores'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocomplemento',
            name='calibre',
            field=models.CharField(blank=True, default='', help_text='Tamaño estándar del producto (HQ, NQ, BQ, PQ, etc.)', max_length=20, verbose_name='Calibre / Serie Dim.'),
        ),
        migrations.AddField(
            model_name='tipocomplemento',
            name='marca',
            field=models.CharField(blank=True, default='', help_text='Fabricante del producto (ej: Boart Longyear, Fordia)', max_length=100, verbose_name='Marca'),
        ),
        migrations.AddIndex(
            model_name='tipocomplemento',
            index=models.Index(fields=['categoria'], name='tipos_compl_categor_3b69ce_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocomplemento',
            index=models.Index(fields=['contrato', 'categoria'], name='tipos_compl_contrat_487b87_idx'),
        ),
    ]
