# Generated by Django 5.0.7 on 2026-03-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0074_add_altura_seriebit_tipocomplemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dia_cambio_guardia',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana en que se realiza el cambio de guardia en este contrato (entrada y salida de mina).', null=True, verbose_name='Día de Cambio de Guardia'),
        ),
        migrations.AlterField(
            model_name='tipocomplemento',
            name='categoria',
            field=models.CharField(blank=True, choices=[('BROCA', 'Broca Diamantada'), ('REAMING_SHELL', 'Reaming Shell'), ('ZAPATA', 'Zapata'), ('CORE_LIFTER', 'Core Lifter')], help_text='Broca Diamantada, Zapata, Reaming Shell o Core Lifter', max_length=20, null=True, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='tipocomplemento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_inicio_labores',
            field=models.DateField(blank=True, help_text='Fecha en que el trabajador empieza a aparacer en el tareo. Diferente a la fecha de contratación de la API.', null=True, verbose_name='Fecha Inicio Labores'),
        ),
    ]
