# Generated by Django 5.0.7 on 2026-03-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0076_add_cargo_headcount_to_trabajador'),
    ]

    operations = [
        # -----------------------------------------------------------------------
        # PASO 1: Usar RunSQL para limpiar la BD (tabla headcount está vacía)
        # La BD tiene aún la estructura FK (cargo_id, maquina_id) porque 0068
        # fue aplicada con --fake. Se corrige aquí con SQL directo.
        # -----------------------------------------------------------------------
        migrations.RunSQL(
            sql=[
                # Eliminar el índice de maquina si existe
                "DROP INDEX IF EXISTS headcount_maquina_53d173_idx;",
                # Eliminar índice de cargo si existe (nombre antiguo)
                "DROP INDEX IF EXISTS headcount_cargo_i_ebf1c1_idx;",
                "DROP INDEX IF EXISTS headcount_cargo_69f577_idx;",
                # Eliminar el unique constraint antiguo
                "ALTER TABLE headcount DROP CONSTRAINT IF EXISTS headcount_contrato_id_cargo_id_maquina_id_834290c9_uniq;",
                # Eliminar FK y columna maquina_id
                "ALTER TABLE headcount DROP CONSTRAINT IF EXISTS headcount_maquina_id_8c87e305_fk_maquinas_id;",
                "ALTER TABLE headcount DROP COLUMN IF EXISTS maquina_id;",
                # Eliminar FK y columna cargo_id, agregar cargo como varchar
                "ALTER TABLE headcount DROP CONSTRAINT IF EXISTS headcount_cargo_id_a043a71b_fk_cargos_id_cargo;",
                "ALTER TABLE headcount DROP COLUMN IF EXISTS cargo_id;",
                "ALTER TABLE headcount ADD COLUMN IF NOT EXISTS cargo VARCHAR(200) NOT NULL DEFAULT '';",
                # Agregar nuevas columnas
                "ALTER TABLE headcount ADD COLUMN IF NOT EXISTS categoria VARCHAR(50) NOT NULL DEFAULT 'OPERADORES';",
                "ALTER TABLE headcount ADD COLUMN IF NOT EXISTS servicio VARCHAR(10) NOT NULL DEFAULT 'DDH';",
                "ALTER TABLE headcount ADD COLUMN IF NOT EXISTS ubicacion VARCHAR(50) NOT NULL DEFAULT 'INTERIOR MINA';",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),

        # -----------------------------------------------------------------------
        # PASO 2: Actualizar el estado de Django para que coincida con la BD
        # -----------------------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='headcount',
                    options={'ordering': ['contrato', 'categoria', 'cargo'], 'verbose_name': 'Headcount', 'verbose_name_plural': 'Headcounts'},
                ),
                migrations.AlterUniqueTogether(
                    name='headcount',
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name='headcount',
                    name='categoria',
                    field=models.CharField(
                        choices=[('LINEA DE MANDO', 'Línea de Mando'), ('CONDUCTORES', 'Conductores'), ('OPERADORES', 'Operadores')],
                        default='OPERADORES', max_length=50, verbose_name='Categoría'
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='headcount',
                    name='servicio',
                    field=models.CharField(
                        choices=[('DDH', 'DDH'), ('SGEO', 'SGEO'), ('SLAB', 'SLAB')],
                        default='DDH', max_length=10, verbose_name='Servicio'
                    ),
                ),
                migrations.AddField(
                    model_name='headcount',
                    name='ubicacion',
                    field=models.CharField(
                        choices=[('INTERIOR MINA', 'Interior Mina'), ('SUPERFICIE', 'Superficie')],
                        default='INTERIOR MINA', max_length=50, verbose_name='Ubicación'
                    ),
                ),
                migrations.AlterField(
                    model_name='headcount',
                    name='cargo',
                    field=models.CharField(
                        choices=[('RESIDENTE', 'Residente'), ('ASISTENTE DE RESIDENTE', 'Asistente de Residente'), ('INGENIERO DE SEGURIDAD', 'Ingeniero de Seguridad'), ('ADMINISTRADOR', 'Administrador'), ('ASISTENTE ADMINISTRATIVO', 'Asistente Administrativo'), ('ASISTENTE LOGISTICO', 'Asistente Logístico'), ('SUPERVISOR OPERATIVO', 'Supervisor Operativo'), ('TECNICO MECANICO', 'Técnico Mecánico'), ('TECNICO ELECTRICISTA', 'Técnico Electricista'), ('TECNICO MECANICO CONDUCTOR SB', 'Técnico Mecánico Conductor SB'), ('CONDUCTOR', 'Conductor'), ('CONDUCTOR SB', 'Conductor SB'), ('PERFORISTA', 'Perforista'), ('AYUDANTE', 'Ayudante'), ('PERFORISTA SB', 'Perforista SB'), ('AYUDANTE SB', 'Ayudante SB'), ('GEOLOGO', 'Geólogo'), ('MUESTRERO ORE CONTROL', 'Muestrero Ore Control'), ('MAESTRO MUESTRERO', 'Maestro Muestrero'), ('AYUDANTE MUESTRERO', 'Ayudante Muestrero'), ('TECNICO GEOLOGIA', 'Técnico Geología'), ('GEOLOGO BD & QA/QC', 'Geólogo BD & QA/QC'), ('ASISTENTE GEOLOGO BD & QA/QC', 'Asistente Geólogo BD & QA/QC'), ('MAESTRO PREPARADOR DE MUESTRAS', 'Maestro Preparador de Muestras'), ('AUXILIAR QA/QC', 'Auxiliar QA/QC'), ('GEOLOGO MINA', 'Geólogo Mina'), ('GEOLOGO DE EXPLORACIONES', 'Geólogo de Exploraciones'), ('SUPERVISOR QA/QC', 'Supervisor QA/QC'), ('LOGISTICO', 'Logístico'), ('AYUDANTE GEOMECANICO', 'Ayudante Geomecánico'), ('TOPOGRAFO', 'Topógrafo'), ('TECNICO MEDICION DENSIDAD', 'Técnico Medición Densidad'), ('MAESTRO MUESTRERO DENSIDAD', 'Maestro Muestrero Densidad'), ('TECNICO DE MAPEO GEOMECANICO', 'Técnico de Mapeo Geomecánico'), ('GEOLOGO DE LOGUEO', 'Geólogo de Logueo'), ('SUPERVISOR DE LABORATORIO', 'Supervisor de Laboratorio')],
                        max_length=200, verbose_name='Cargo'
                    ),
                ),
                migrations.RemoveField(model_name='headcount', name='maquina'),
                migrations.AlterUniqueTogether(
                    name='headcount',
                    unique_together={('contrato', 'cargo', 'categoria', 'servicio', 'ubicacion')},
                ),
            ],
        ),

        # -----------------------------------------------------------------------
        # PASO 3: Crear los índices nuevos y el unique constraint en la BD
        # -----------------------------------------------------------------------
        migrations.RunSQL(
            sql=[
                "CREATE INDEX IF NOT EXISTS headcount_cargo_69f577_idx ON headcount (cargo);",
                "CREATE INDEX IF NOT EXISTS headcount_categor_238cea_idx ON headcount (categoria);",
                "CREATE INDEX IF NOT EXISTS headcount_servici_723fde_idx ON headcount (servicio);",
                "CREATE INDEX IF NOT EXISTS headcount_ubicaci_0005b7_idx ON headcount (ubicacion);",
                "ALTER TABLE headcount ADD CONSTRAINT headcount_contrato_id_cargo_categoria_servicio_ubicacion_uniq UNIQUE (contrato_id, cargo, categoria, servicio, ubicacion);",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]

