# Generated by Django 5.0.7 on 2026-03-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0077_headcount_add_categoria_servicio_ubicacion_remove_maquina'),
    ]

    operations = [
        # Los índices/constraints anteriores ya fueron manejados en 0077 con RunSQL.
        # Usamos SeparateDatabaseAndState para sincronizar solo el estado de Django.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='headcount',
                    unique_together=set(),
                ),
            ]
        ),

        # Agregar campo nivel en BD
        migrations.AddField(
            model_name='headcount',
            name='nivel',
            field=models.CharField(blank=True, choices=[('I', 'Nivel I'), ('II', 'Nivel II'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], default='', help_text='Nivel del cargo (I, II, Junior, Senior)', max_length=10, verbose_name='Nivel'),
        ),

        # Actualizar choices (solo estado Django, no genera SQL)
        migrations.AlterField(
            model_name='headcount',
            name='categoria',
            field=models.CharField(choices=[('LINEA DE MANDO', 'Línea de Mando'), ('OPERATIVO', 'Operativo'), ('VACACIONISTA', 'Vacacionista')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='servicio',
            field=models.CharField(choices=[('DDH', 'DDH'), ('SGEO', 'SGEO'), ('LAB', 'LAB')], default='DDH', max_length=10, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='ubicacion',
            field=models.CharField(choices=[('SUPERFICIE', 'Superficie'), ('MINA', 'Mina'), ('GENERAL', 'General')], default='SUPERFICIE', max_length=50, verbose_name='Ubicación'),
        ),

        # Recrear el unique constraint en BD incluyendo nivel
        migrations.RunSQL(
            sql=[
                "ALTER TABLE headcount DROP CONSTRAINT IF EXISTS headcount_contrato_id_cargo_categoria_servicio_ubicacion_uniq;",
                "ALTER TABLE headcount ADD CONSTRAINT headcount_contrato_cargo_categoria_servicio_ubicacion_nivel_uniq UNIQUE (contrato_id, cargo, categoria, servicio, ubicacion, nivel);",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Actualizar estado Django con el nuevo unique_together
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='headcount',
                    unique_together={('contrato', 'cargo', 'categoria', 'servicio', 'ubicacion', 'nivel')},
                ),
            ]
        ),
    ]
