# Generated by Django 5.0.7 on 2026-04-08 23:36
# Rewritten: only add turno_inicio to contratos.
# All other operations from the original were already applied via
# the parallel branch (0079_fechacerrada, 0080_trabajador_fecha_cese, etc.)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drilling", "0084_add_maintenance_roles"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE contratos ADD COLUMN IF NOT EXISTS turno_inicio VARCHAR(2) NOT NULL DEFAULT 'TD';",
                    reverse_sql="ALTER TABLE contratos DROP COLUMN IF EXISTS turno_inicio;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="contrato",
                    name="turno_inicio",
                    field=models.CharField(
                        choices=[
                            ("TD", "Inicia con Turno Dia (primeros 7 dias son TD)"),
                            ("TN", "Inicia con Turno Noche (primeros 7 dias son TN)"),
                        ],
                        default="TD",
                        help_text="Define si las guardias empiezan con TD o TN.",
                        max_length=2,
                        verbose_name="Turno de Inicio de Guardia",
                    ),
                ),
            ],
        ),
    ]
