# Generated by Django 5.2.6 on 2026-04-06 05:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0084_add_maintenance_roles'),
    ]

    operations = [
        # SafeCreateModel: usa IF NOT EXISTS para tolerar tabla preexistente
        # (puede ocurrir si un run anterior de esta migración abortó a mitad)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "fecha_cerrada" (
                            "id" bigserial NOT NULL PRIMARY KEY,
                            "fecha" date NOT NULL,
                            "fecha_cierre" timestamp with time zone NOT NULL,
                            "motivo" text NOT NULL
                        );
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "fecha_cerrada";',
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name='FechaCerrada',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('fecha', models.DateField()),
                        ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                        ('motivo', models.TextField(blank=True)),
                    ],
                    options={
                        'verbose_name': 'Fecha Cerrada',
                        'verbose_name_plural': 'Fechas Cerradas',
                        'db_table': 'fecha_cerrada',
                    },
                )
            ],
        ),
        migrations.CreateModel(
            name='TareoClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('total_trabajadores', models.IntegerField(default=0)),
                ('total_dias_trabajo', models.IntegerField(default=0)),
                ('total_descansos', models.IntegerField(default=0)),
                ('total_faltas', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tareo_closure',
            },
        ),
        migrations.CreateModel(
            name='TareoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('TRABAJO', 'Trabajo'), ('TD', 'Turno Día'), ('TN', 'Turno Noche'), ('DESCANSO', 'Descanso'), ('FALTA', 'Falta'), ('VACACIONES', 'Vacaciones'), ('PERMISO', 'Permiso')], db_index=True, default='TRABAJO', max_length=20)),
                ('tipo', models.CharField(choices=[('PROY', 'Proyección'), ('REAL', 'Real')], db_index=True, default='REAL', max_length=10)),
                ('guardia_snapshot', models.CharField(blank=True, max_length=1, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrada Tareo',
                'verbose_name_plural': 'Entradas Tareo',
                'db_table': 'tareo_entry',
            },
        ),
        migrations.CreateModel(
            name='TareoEntryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('tipo_anterior', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_nuevo', models.CharField(blank=True, max_length=10, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tareo_entry_audit',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='TareoPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio periodo')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin periodo')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_REVISION', 'En Revisión'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tareo_period',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.AlterModelOptions(
            name='asistenciadiaria',
            options={'ordering': ['-fecha', 'trabajador__apepat', 'trabajador__nombres'], 'verbose_name': 'Asistencia Diaria', 'verbose_name_plural': 'Asistencias Diarias'},
        ),
        migrations.RemoveConstraint(
            model_name='asistenciadiaria',
            name='unique_empleado_fecha',
        ),
        migrations.RemoveIndex(
            model_name='asistenciadiaria',
            name='idx_empleado_fecha',
        ),
        migrations.RemoveIndex(
            model_name='headcount',
            name='headcount_maquina_53d173_idx',
        ),
        migrations.RenameIndex(
            model_name='mantenimientomaquina',
            new_name='mantenimien_maquina_08e73c_idx',
            old_name='mant_maq_maq_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='mantenimientomaquina',
            new_name='mantenimien_tipo_6a2a04_idx',
            old_name='mant_maq_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='mantenimientomaquina',
            new_name='mantenimien_estado__175f78_idx',
            old_name='mant_maq_estado_ot_idx',
        ),
        migrations.RenameIndex(
            model_name='mantenimientomaquina',
            new_name='mantenimien_fecha_i_bc913c_idx',
            old_name='mant_maq_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='metadiariamaquina',
            new_name='meta_diaria_maquina_b729e6_idx',
            old_name='meta_diaria_maquina_idx',
        ),
        migrations.RenameIndex(
            model_name='metaturno',
            new_name='meta_turno_maquina_e4456d_idx',
            old_name='meta_turno_maq_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='programacionmes',
            new_name='programacio_año_ceb91d_idx',
            old_name='prog_mes_anio_mes_idx',
        ),
        migrations.RenameIndex(
            model_name='programacionmes',
            new_name='programacio_maquina_bc663f_idx',
            old_name='prog_mes_maquina_idx',
        ),
        migrations.RemoveField(
            model_name='asistenciadiaria',
            name='empleado',
        ),
        migrations.AddField(
            model_name='asistenciadiaria',
            name='trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_diarias', to='drilling.trabajador', verbose_name='Trabajador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sondaje',
            name='es_cobrable',
            field=models.BooleanField(default=True, help_text='Si es False, los metros de este sondaje NO se incluyen en la valorización al cliente', verbose_name='Metros cobrables'),
        ),
        migrations.AddField(
            model_name='sondaje',
            name='motivo_cierre',
            field=models.CharField(blank=True, choices=[('', '---'), ('META_ALCANZADA', 'Meta alcanzada (profundidad planificada)'), ('DESVIADO', 'Sondaje desviado'), ('ACCIDENTE_POZO', 'Accidente de pozo (herramientas atrapadas, colapso)'), ('DECISION_CLIENTE', 'Decisión del cliente'), ('CONDICIONES_GEOLOGICAS', 'Condiciones geológicas adversas'), ('FALLA_MECANICA', 'Falla mecánica mayor'), ('OTRO', 'Otro motivo')], default='', help_text='Razón por la que el sondaje dejó de perforarse', max_length=30, verbose_name='Motivo de cierre'),
        ),
        migrations.AddField(
            model_name='sondaje',
            name='observaciones_cierre',
            field=models.TextField(blank=True, default='', help_text='Detalle del motivo de cierre, autorización, acuerdos con el cliente', verbose_name='Observaciones de cierre'),
        ),
        migrations.AddField(
            model_name='sondaje',
            name='profundidad_alcanzada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros reales perforados al momento de cierre', max_digits=8, null=True, verbose_name='Profundidad alcanzada (m)'),
        ),
        migrations.AddField(
            model_name='sondaje',
            name='responsable_cierre',
            field=models.CharField(blank=True, choices=[('', '---'), ('CONTRATISTA', 'Contratista (nosotros)'), ('CLIENTE', 'Cliente'), ('FUERZA_MAYOR', 'Fuerza mayor / geología'), ('COMPARTIDA', 'Responsabilidad compartida')], default='', help_text='Quién asume la responsabilidad/costo del cierre', max_length=20, verbose_name='Responsabilidad del cierre'),
        ),
        migrations.AddField(
            model_name='sondaje',
            name='sondaje_padre',
            field=models.ForeignKey(blank=True, help_text='Si este sondaje reemplaza a uno desviado/abandonado, seleccionar el original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reperforaciones', to='drilling.sondaje', verbose_name='Sondaje padre (si es reperforación)'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_cese',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cese'),
        ),
        migrations.AlterField(
            model_name='asistenciadiaria',
            name='estado',
            field=models.CharField(choices=[('T', 'TRABAJADO'), ('TD', 'TRABAJADO DIA'), ('TN', 'TRABAJADO NOCHE'), ('TI', 'TRABAJADO + INCENTIVO POR SUPERAR METROS'), ('DL', 'DIA LIBRE'), ('DA', 'DIA APOYO'), ('PT', 'PERMISO PATERNIDAD'), ('DM', 'DESCANSO MEDICO'), ('SB', 'STAND BY'), ('SUB', 'SUBSIDIO'), ('I', 'INDUCCION'), ('IV', 'INDUCCION VIRTUAL'), ('R', 'RECORRIDO'), ('F', 'FALTA'), ('PT1', 'PERMISO PATERNIDAD'), ('S', 'SUSPENSION'), ('V', 'VACACIONES'), ('LSG', 'LICENCIA SIN GOCE'), ('C', 'CESADO'), ('TC1', 'TRABAJO EN CALIENTE 1HE'), ('LFC', 'LICENCIA POR FALLECIMIENTO'), ('DA1', 'DIA DE APOYO CON 1 HORA EXTRA'), ('IVN', 'INDUCCION VIRTUAL'), ('LCG', 'LICENCIA CON GOCE'), ('LOG', 'LICENCIA CON GOCE')], db_index=True, default='TRABAJO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='asistenciatrabajador',
            name='estado',
            field=models.CharField(choices=[('T', 'TRABAJADO'), ('TD', 'TRABAJADO DIA'), ('TN', 'TRABAJADO NOCHE'), ('TI', 'TRABAJADO + INCENTIVO POR SUPERAR METROS'), ('DL', 'DIA LIBRE'), ('DA', 'DIA APOYO'), ('PT', 'PERMISO PATERNIDAD'), ('DM', 'DESCANSO MEDICO'), ('SB', 'STAND BY'), ('SUB', 'SUBSIDIO'), ('I', 'INDUCCION'), ('IV', 'INDUCCION VIRTUAL'), ('R', 'RECORRIDO'), ('F', 'FALTA'), ('PT1', 'PERMISO PATERNIDAD'), ('S', 'SUSPENSION'), ('V', 'VACACIONES'), ('LSG', 'LICENCIA SIN GOCE'), ('C', 'CESADO'), ('TC1', 'TRABAJO EN CALIENTE 1HE'), ('LFC', 'LICENCIA POR FALLECIMIENTO'), ('DA1', 'DIA DE APOYO CON 1 HORA EXTRA'), ('IVN', 'INDUCCION VIRTUAL'), ('LCG', 'LICENCIA CON GOCE'), ('LOG', 'LICENCIA CON GOCE')], default='TRABAJADO', max_length=30, verbose_name='Estado de asistencia'),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='cantidad_requerida',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad requerida'),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='cargo',
            field=models.CharField(choices=[('RESIDENTE', 'Residente'), ('ASISTENTE DE RESIDENTE', 'Asistente de Residente'), ('INGENIERO DE SEGURIDAD', 'Ingeniero de Seguridad'), ('ADMINISTRADOR', 'Administrador'), ('ASISTENTE ADMINISTRATIVO', 'Asistente Administrativo'), ('ASISTENTE LOGISTICO', 'Asistente Logístico'), ('SUPERVISOR OPERATIVO', 'Supervisor Operativo'), ('TECNICO MECANICO', 'Técnico Mecánico'), ('TECNICO MECANICO I', 'Técnico Mecánico I'), ('TECNICO MECANICO II', 'Técnico Mecánico II'), ('TECNICO ELECTRICISTA', 'Técnico Electricista'), ('TECNICO MECANICO CONDUCTOR SB', 'Técnico Mecánico Conductor SB'), ('CONDUCTOR', 'Conductor'), ('CONDUCTOR SB', 'Conductor SB'), ('PERFORISTA', 'Perforista'), ('AYUDANTE', 'Ayudante'), ('PERFORISTA SB', 'Perforista SB'), ('AYUDANTE SB', 'Ayudante SB'), ('GEOLOGO', 'Geólogo'), ('MUESTRERO ORE CONTROL', 'Muestrero Ore Control'), ('MAESTRO MUESTRERO', 'Maestro Muestrero'), ('AYUDANTE MUESTRERO', 'Ayudante Muestrero'), ('TECNICO GEOLOGIA', 'Técnico Geología'), ('GEOLOGO BD & QA/QC', 'Geólogo BD & QA/QC'), ('ASISTENTE GEOLOGO BD & QA/QC', 'Asistente Geólogo BD & QA/QC'), ('MAESTRO PREPARADOR DE MUESTRAS', 'Maestro Preparador de Muestras'), ('AUXILIAR QA/QC', 'Auxiliar QA/QC'), ('GEOLOGO MINA', 'Geólogo Mina'), ('GEOLOGO DE EXPLORACIONES', 'Geólogo de Exploraciones'), ('SUPERVISOR QA/QC', 'Supervisor QA/QC'), ('LOGISTICO', 'Logístico'), ('AYUDANTE GEOMECANICO', 'Ayudante Geomecánico'), ('TOPOGRAFO', 'Topógrafo'), ('TECNICO MEDICION DENSIDAD', 'Técnico Medición Densidad'), ('MAESTRO MUESTRERO DENSIDAD', 'Maestro Muestrero Densidad'), ('TECNICO DE MAPEO GEOMECANICO', 'Técnico de Mapeo Geomecánico'), ('GEOLOGO DE LOGUEO', 'Geólogo de Logueo'), ('SUPERVISOR DE LABORATORIO', 'Supervisor de Laboratorio'), ('SUPERVISOR DE MUESTREO', 'Supervisor de Muestreo')], max_length=200),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='categoria',
            field=models.CharField(choices=[('LINEA DE MANDO', 'Línea de Mando'), ('OPERATIVO', 'Operativo'), ('CONDUCTORES', 'Conductores'), ('VACACIONISTA', 'Vacacionista')], default='OPERATIVO', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='nivel',
            field=models.CharField(blank=True, choices=[('I', 'Nivel I'), ('II', 'Nivel II'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], default=None, max_length=20, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='ubicacion',
            field=models.CharField(choices=[('SUPERFICIE', 'Superficie'), ('MINA', 'Mina'), ('GENERAL', 'General')], default='GENERAL', max_length=50, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='tiempo_parada_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas que la máquina estuvo fuera de servicio', max_digits=8, null=True, verbose_name='Tiempo de parada (hrs)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='horometro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horómetro (hrs)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='intervalo_mantenimiento_horas',
            field=models.DecimalField(decimal_places=2, default=250, help_text='Cada cuántas horas se realiza mantenimiento preventivo', max_digits=8, verbose_name='Intervalo mtto. (hrs)'),
        ),
        migrations.AlterField(
            model_name='metadiariamaquina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metaturno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programacionmes',
            name='dia_inicio',
            field=models.DateField(help_text='Fecha en que la máquina inicia operaciones en este período', verbose_name='Día de inicio'),
        ),
        migrations.AlterField(
            model_name='programacionmes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programacionmes',
            name='mes',
            field=models.IntegerField(help_text='Mes del día 25 (fin del período). Ej: abril 2026 → mes=4, año=2026', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='programacionmes',
            name='meta_metros',
            field=models.DecimalField(decimal_places=2, help_text='Metraje objetivo total del período', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Meta metros (mensual)'),
        ),
        migrations.AlterField(
            model_name='sondaje',
            name='profundidad',
            field=models.DecimalField(decimal_places=2, help_text='Profundidad planificada en metros', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('3000.00'))]),
        ),
        migrations.AlterField(
            model_name='trabajadorcontratohistorial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='asistenciadiaria',
            index=models.Index(fields=['trabajador', 'fecha'], name='idx_trabajador_fecha'),
        ),
        migrations.AddIndex(
            model_name='headcount',
            index=models.Index(fields=['categoria'], name='headcount_categor_238cea_idx'),
        ),
        migrations.AddIndex(
            model_name='headcount',
            index=models.Index(fields=['servicio'], name='headcount_servici_723fde_idx'),
        ),
        migrations.AddIndex(
            model_name='headcount',
            index=models.Index(fields=['ubicacion'], name='headcount_ubicaci_0005b7_idx'),
        ),
        migrations.AddIndex(
            model_name='sondaje',
            index=models.Index(fields=['es_cobrable'], name='sondajes_es_cobr_3acefe_idx'),
        ),
        migrations.AddIndex(
            model_name='sondaje',
            index=models.Index(fields=['sondaje_padre'], name='sondajes_sondaje_2e183e_idx'),
        ),
        migrations.AddIndex(
            model_name='sondaje',
            index=models.Index(fields=['motivo_cierre'], name='sondajes_motivo__a98e4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistenciadiaria',
            constraint=models.UniqueConstraint(fields=('trabajador', 'fecha'), name='unique_trabajador_fecha'),
        ),
        migrations.AddField(
            model_name='fechacerrada',
            name='cerrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechas_cerradas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fechacerrada',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechas_cerradas', to='drilling.contrato'),
        ),
        migrations.AddField(
            model_name='tareoclosure',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareoentry',
            name='maquina_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drilling.maquina'),
        ),
        migrations.AddField(
            model_name='tareoentry',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareoentry',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareo_entries', to='drilling.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='tareoentryaudit',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='drilling.tareoentry'),
        ),
        migrations.AddField(
            model_name='tareoentryaudit',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareoperiod',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareo_periods', to='drilling.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='tareoentry',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='drilling.tareoperiod', verbose_name='Periodo operativo'),
        ),
        migrations.AddField(
            model_name='tareoclosure',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closure', to='drilling.tareoperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='fechacerrada',
            unique_together={('contrato', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='tareoperiod',
            unique_together={('contrato', 'anio', 'mes')},
        ),
        migrations.AddIndex(
            model_name='tareoentry',
            index=models.Index(fields=['trabajador', 'fecha'], name='idx_tareo_trab_fecha'),
        ),
        migrations.AddIndex(
            model_name='tareoentry',
            index=models.Index(fields=['fecha', 'estado'], name='idx_tareo_fecha_estado'),
        ),
        migrations.AlterUniqueTogether(
            name='tareoentry',
            unique_together={('trabajador', 'fecha')},
        ),
    ]
