# Generated by Django 5.2.6 on 2026-04-08 02:51
# Modified to be idempotent: tolerates fields already existing in DB
# (use when 0085 was faked due to DB/state divergence)

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class SafeAddField(migrations.AddField):
    """AddField que no falla si la columna ya existe en la base de datos."""
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from django.db import connection
        to_model = to_state.apps.get_model(app_label, self.model_name)
        with connection.cursor() as cursor:
            existing_cols = {col.name for col in
                             connection.introspection.get_table_description(cursor, to_model._meta.db_table)}
        field = to_model._meta.get_field(self.name)
        if field.column not in existing_cols:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class SafeAlterField(migrations.AlterField):
    """AlterField que no falla si la columna no existe en la base de datos."""
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from django.db import connection
        to_model = to_state.apps.get_model(app_label, self.model_name)
        with connection.cursor() as cursor:
            existing_cols = {col.name for col in
                             connection.introspection.get_table_description(cursor, to_model._meta.db_table)}
        field = to_model._meta.get_field(self.name)
        if field.column in existing_cols:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0085_sondaje_desvio_cobrabilidad'),
    ]

    operations = [
        # ─── Campos de 0085 que pueden faltar si se aplicó con --fake ────────────
        # Usamos SeparateDatabaseAndState con state_operations vacías porque la
        # migración 0085 (fakeada) ya actualizó el estado interno de Django.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                SafeAddField(
                    model_name='sondaje',
                    name='es_cobrable',
                    field=models.BooleanField(default=True, verbose_name='Metros cobrables'),
                ),
                SafeAddField(
                    model_name='sondaje',
                    name='motivo_cierre',
                    field=models.CharField(
                        blank=True, default='', max_length=30,
                        verbose_name='Motivo de cierre',
                        choices=[
                            ('', '---'),
                            ('META_ALCANZADA', 'Meta alcanzada (profundidad planificada)'),
                            ('DESVIADO', 'Sondaje desviado'),
                            ('ACCIDENTE_POZO', 'Accidente de pozo (herramientas atrapadas, colapso)'),
                            ('DECISION_CLIENTE', 'Decisión del cliente'),
                            ('CONDICIONES_GEOLOGICAS', 'Condiciones geológicas adversas'),
                            ('FALLA_MECANICA', 'Falla mecánica mayor'),
                            ('OTRO', 'Otro motivo'),
                        ],
                    ),
                ),
                SafeAddField(
                    model_name='sondaje',
                    name='observaciones_cierre',
                    field=models.TextField(blank=True, default='', verbose_name='Observaciones de cierre'),
                ),
                SafeAddField(
                    model_name='sondaje',
                    name='profundidad_alcanzada',
                    field=models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True,
                        verbose_name='Profundidad alcanzada (m)',
                    ),
                ),
                SafeAddField(
                    model_name='sondaje',
                    name='responsable_cierre',
                    field=models.CharField(
                        blank=True, default='', max_length=20,
                        verbose_name='Responsabilidad del cierre',
                        choices=[
                            ('', '---'),
                            ('CONTRATISTA', 'Contratista (nosotros)'),
                            ('CLIENTE', 'Cliente'),
                            ('FUERZA_MAYOR', 'Fuerza mayor / geología'),
                            ('COMPARTIDA', 'Responsabilidad compartida'),
                        ],
                    ),
                ),
                SafeAddField(
                    model_name='sondaje',
                    name='sondaje_padre',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reperforaciones',
                        to='drilling.sondaje',
                        verbose_name='Sondaje padre (si es reperforación)',
                    ),
                ),
            ],
            state_operations=[],  # Estado ya correcto desde 0085 (fakeado)
        ),

        # ─── Campo nuevo: punto de desvío ─────────────────────────────────────
        SafeAddField(
            model_name='sondaje',
            name='profundidad_desvio',
            field=models.DecimalField(
                blank=True, decimal_places=2,
                help_text='Metros desde superficie hasta donde el sondaje era recto y cobrable. '
                          'Ej: 100m → los primeros 100m son cobrables, el resto se descarta. '
                          'Dejar vacío si el sondaje completo es cobrable (o es_cobrable=False para pérdida total).',
                max_digits=8, null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                verbose_name='Profundidad del desvío (m)',
            ),
        ),

        # ─── Actualizar definiciones de campos (help_text mejorado) ──────────
        SafeAlterField(
            model_name='sondaje',
            name='es_cobrable',
            field=models.BooleanField(
                default=True,
                help_text='True = sondaje tiene metros cobrables. False = pérdida total (0 metros al cliente). '
                          'Para desvíos parciales, usar profundidad_desvio en lugar de desmarcar este campo.',
                verbose_name='Metros cobrables',
            ),
        ),
        SafeAlterField(
            model_name='sondaje',
            name='profundidad_alcanzada',
            field=models.DecimalField(
                blank=True, decimal_places=2,
                help_text='Metros totales perforados al momento de cierre (incluyendo zona desviada)',
                max_digits=8, null=True,
                verbose_name='Profundidad alcanzada (m)',
            ),
        ),
    ]
