# Generated by Django 5.2.6 on 2026-04-08 02:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0085_sondaje_desvio_cobrabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondaje',
            name='profundidad_desvio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros desde superficie hasta donde el sondaje era recto y cobrable. Ej: 100m → los primeros 100m son cobrables, el resto se descarta. Dejar vacío si el sondaje completo es cobrable (o es_cobrable=False para pérdida total).', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Profundidad del desvío (m)'),
        ),
        migrations.AlterField(
            model_name='sondaje',
            name='es_cobrable',
            field=models.BooleanField(default=True, help_text='True = sondaje tiene metros cobrables. False = pérdida total (0 metros al cliente). Para desvíos parciales, usar profundidad_desvio en lugar de desmarcar este campo.', verbose_name='Metros cobrables'),
        ),
        migrations.AlterField(
            model_name='sondaje',
            name='profundidad_alcanzada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros totales perforados al momento de cierre (incluyendo zona desviada)', max_digits=8, null=True, verbose_name='Profundidad alcanzada (m)'),
        ),
    ]
