# Generated by Django 5.0.7 on 2026-04-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0085_add_turno_inicio_contrato'),
        ('drilling', '0086_sondaje_profundidad_desvio'),
    ]

    operations = [
    ]
