# Generated by Django 5.0.7 on 2026-04-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0087_merge_20260414_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='emo_estado',
            field=models.CharField(blank=True, help_text='Ej: APTO, APTO CON RESTRICCIONES, NO APTO', max_length=100, verbose_name='EMO Estado'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='emo_fecha_realizado',
            field=models.DateField(blank=True, null=True, verbose_name='EMO Fecha de Realización'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='emo_fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='EMO Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='emo_programacion',
            field=models.DateField(blank=True, null=True, verbose_name='EMO Programación Próximo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fotocheck_fecha_caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fotocheck Fecha Caducidad'),
        ),
        migrations.AlterField(
            model_name='asistenciadiaria',
            name='estado',
            field=models.CharField(choices=[('T', 'TRABAJADO'), ('TD', 'TRABAJADO DIA'), ('TN', 'TRABAJADO NOCHE'), ('TI', 'TRABAJADO + INCENTIVO POR SUPERAR METROS'), ('DL', 'DIA LIBRE'), ('DA', 'DIA APOYO'), ('PT', 'PERMISO PATERNIDAD'), ('DM', 'DESCANSO MEDICO'), ('SB', 'STAND BY'), ('SUB', 'SUBSIDIO'), ('I', 'INDUCCION'), ('IV', 'INDUCCION VIRTUAL'), ('R', 'RECORRIDO'), ('F', 'FALTA'), ('PT1', 'PERMISO PATERNIDAD'), ('S', 'SUSPENSION'), ('V', 'VACACIONES'), ('LSG', 'LICENCIA SIN GOCE'), ('C', 'CESADO'), ('TC1', 'TRABAJO EN CALIENTE 1HE'), ('LFC', 'LICENCIA POR FALLECIMIENTO'), ('DA1', 'DIA DE APOYO CON 1 HORA EXTRA'), ('IVN', 'INDUCCION VIRTUAL'), ('LCG', 'LICENCIA CON GOCE'), ('LOG', 'LICENCIA CON GOCE')], db_index=True, default='T', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='turno_inicio',
            field=models.CharField(choices=[('TD', 'Inicia con Turno Día (primeros 7 días son TD)'), ('TN', 'Inicia con Turno Noche (primeros 7 días son TN)')], default='TD', help_text='Define si las guardias empiezan con Turno Día o Turno Noche al inicio del ciclo laboral.', max_length=2, verbose_name='Turno de Inicio de Guardia'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fotocheck_fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fotocheck Fecha Emisión'),
        ),
    ]
