# Generated by Django 5.0.7 on 2026-04-14 18:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0088_add_emo_fields_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Bono')),
                ('categoria', models.CharField(choices=[('REMUNERATIVO', 'Bono Remunerativo'), ('EXTRAORDINARIO', 'Bono Extraordinario')], max_length=20, verbose_name='Categoría')),
                ('tipo_calculo', models.CharField(choices=[('FIJO', 'Monto Fijo — (monto_mensual / días_base) × días_trabajados'), ('MULTI_CONCEPTO', 'Múltiples Conceptos con Puntaje (0-100)'), ('POR_DIA', 'Monto Directo por Día Trabajado'), ('ESCALONADO', 'Escalonado por Rango de Días')], max_length=20, verbose_name='Tipo de Cálculo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_sistema', models.BooleanField(default=False, help_text='Los bonos del sistema (B1-B4) no se pueden eliminar')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Bono',
                'verbose_name_plural': 'Tipos de Bono',
                'db_table': 'payroll_tipo_bono',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionBonoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_base_mensual', models.DecimalField(decimal_places=2, help_text='Monto máximo mensual del bono (para FIJO y MULTI_CONCEPTO)', max_digits=10, verbose_name='Monto Base Mensual (S/)')),
                ('monto_por_dia', models.DecimalField(decimal_places=2, default=0, help_text='Solo para tipo POR_DIA', max_digits=8, verbose_name='Monto por Día (S/)')),
                ('usa_dias_regimen', models.BooleanField(default=True, help_text='Si es True, se calculan los días base según el régimen del trabajador. Si es False, usa el valor fijo.', verbose_name='Usar días del régimen laboral')),
                ('dias_base_fijo', models.PositiveSmallIntegerField(blank=True, help_text='Días base fijos (solo si no usa régimen). Ej: 30', null=True, verbose_name='Días Base Fijo')),
                ('activo', models.BooleanField(default=True)),
                ('vigencia_desde', models.DateField(verbose_name='Vigencia Desde')),
                ('vigencia_hasta', models.DateField(blank=True, null=True, verbose_name='Vigencia Hasta')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_bono', to='drilling.contrato')),
                ('tipo_bono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones', to='drilling.tipobono')),
            ],
            options={
                'verbose_name': 'Configuración de Bono por Contrato',
                'verbose_name_plural': 'Configuraciones de Bono por Contrato',
                'db_table': 'payroll_config_bono_contrato',
                'ordering': ['contrato', 'tipo_bono__codigo'],
                'unique_together': {('contrato', 'tipo_bono')},
            },
        ),
        migrations.CreateModel(
            name='EscalaBonoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_desde', models.PositiveSmallIntegerField(verbose_name='Desde (días)')),
                ('dias_hasta', models.PositiveSmallIntegerField(verbose_name='Hasta (días)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (S/)')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='drilling.configuracionbonocontrato')),
            ],
            options={
                'verbose_name': 'Escala de Bono',
                'verbose_name_plural': 'Escalas de Bono',
                'db_table': 'payroll_escala_bono_contrato',
                'ordering': ['configuracion', 'dias_desde'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoBono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio Período')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin Período')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CALCULADO', 'Calculado'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=15)),
                ('calculado_at', models.DateTimeField(blank=True, null=True)),
                ('aprobado_at', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_bono_aprobados', to=settings.AUTH_USER_MODEL)),
                ('calculado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_bono_calculados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_bono', to='drilling.contrato')),
            ],
            options={
                'verbose_name': 'Período de Bonos',
                'verbose_name_plural': 'Períodos de Bonos',
                'db_table': 'payroll_periodo_bono',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('contrato', 'anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ConceptoBono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Concepto')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('peso_default', models.DecimalField(decimal_places=2, default=0, help_text='Peso relativo del concepto. Los pesos del bono deben sumar 100%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso Default (%)')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('tipo_bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='drilling.tipobono')),
            ],
            options={
                'verbose_name': 'Concepto de Bono',
                'verbose_name_plural': 'Conceptos de Bono',
                'db_table': 'payroll_concepto_bono',
                'ordering': ['tipo_bono', 'orden'],
                'unique_together': {('tipo_bono', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='BonoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0, verbose_name='Días Trabajados')),
                ('dias_base', models.PositiveSmallIntegerField(default=0, verbose_name='Días Base')),
                ('factor_cumplimiento', models.DecimalField(decimal_places=4, default=1, help_text='1.0000 = 100% cumplimiento. Para FIJO siempre es 1.0', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Factor de Cumplimiento')),
                ('monto_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Calculado (S/)')),
                ('monto_ajuste', models.DecimalField(decimal_places=2, default=0, help_text='Monto positivo o negativo de ajuste manual', max_digits=10, verbose_name='Ajuste Manual (S/)')),
                ('monto_final', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Final (S/)')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonos_calculados', to='drilling.trabajador')),
                ('configuracion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='drilling.configuracionbonocontrato')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='drilling.periodobono')),
                ('tipo_bono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='drilling.tipobono')),
            ],
            options={
                'verbose_name': 'Bono de Trabajador',
                'verbose_name_plural': 'Bonos de Trabajadores',
                'db_table': 'payroll_bono_trabajador',
                'ordering': ['periodo', 'trabajador__apepat', 'tipo_bono__codigo'],
                'unique_together': {('periodo', 'trabajador', 'tipo_bono')},
            },
        ),
        migrations.CreateModel(
            name='BonoTrabajadorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, help_text='Calificación del concepto: 0=no cumple, 100=cumplimiento total', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntaje (0-100)')),
                ('monto_max_concepto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Máx. Concepto (S/)')),
                ('monto_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Calculado (S/)')),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='drilling.bonotrabajador')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='drilling.conceptobono')),
            ],
            options={
                'verbose_name': 'Detalle de Bono',
                'verbose_name_plural': 'Detalles de Bono',
                'db_table': 'payroll_bono_trabajador_detalle',
                'ordering': ['bono', 'concepto__orden'],
                'unique_together': {('bono', 'concepto')},
            },
        ),
        migrations.CreateModel(
            name='ConceptoBonoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto máximo por este concepto en el mes', max_digits=10, verbose_name='Monto Máximo (S/)')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_contrato', to='drilling.conceptobono')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_contrato', to='drilling.configuracionbonocontrato')),
            ],
            options={
                'verbose_name': 'Concepto de Bono por Contrato',
                'verbose_name_plural': 'Conceptos de Bono por Contrato',
                'db_table': 'payroll_concepto_bono_contrato',
                'unique_together': {('configuracion', 'concepto')},
            },
        ),
    ]
