# Generated by Django 5.0.7 on 2026-04-14 23:31

from django.db import migrations


def seed_bonos_sistema(apps, schema_editor):
    """Crea los 3 cuadros de bonos del sistema con sus secciones y criterios."""
    TipoBono = apps.get_model('drilling', 'TipoBono')
    ConceptoBono = apps.get_model('drilling', 'ConceptoBono')
    CriterioBono = apps.get_model('drilling', 'CriterioBono')

    # ==========================================================
    # CUADRO ADMINISTRACIÓN — Administradoras + Asist. Admin.
    # ==========================================================
    bono_adm = TipoBono.objects.create(
        codigo='ADM',
        nombre='Bono Administración',
        categoria='REMUNERATIVO',
        tipo_calculo='MULTI_CONCEPTO',
        descripcion='Bono para personal administrativo: Administradoras y Asistentes Administrativos.',
        es_sistema=True,
        activo=True,
        cargos_aplicables=['ADMINISTRADOR', 'ASISTENTE ADMINISTRATIV', 'AUXILIAR ADMINISTRATIV'],
    )

    # Sección 1: Gestión Humana (30%)
    sec_gh = ConceptoBono.objects.create(
        tipo_bono=bono_adm, codigo='GH', nombre='Gestión Humana',
        es_obligatorio=True, peso_default=30, orden=1,
    )
    criterios_gh = [
        'Control de asistencia Sem 1',
        'Control de asistencia Sem 2',
        'Conciliación de bonos y energía',
        'Control de pago / tardanzas',
        'Control de asistencia Sem 3',
        '1ra Revisión de tareo Sem 1-2',
        'Cierre del mes (días de cada mes)',
        'Confirmación de salidas y entradas',
        '2da Revisión de tareo Sem 3-4',
        'Seguridad de cada mes',
        'Control de personal',
        'Asignación de campamento',
        'Inspección de campamento',
        'Inspección de comedor',
        'Cumplidos de vestuario',
        'Contratos de personal 1RA R.',
        'Actualización de HC 1RA',
        'Actualización de HC 2RA',
        'Actualización de HC 3RA',
    ]
    for i, nombre in enumerate(criterios_gh, 1):
        CriterioBono.objects.create(concepto=sec_gh, nombre=nombre, orden=i, activo=True)

    # Sección 2: Gestión Administrativa (30%)
    sec_ga = ConceptoBono.objects.create(
        tipo_bono=bono_adm, codigo='GA', nombre='Gestión Administrativa',
        es_obligatorio=True, peso_default=30, orden=2,
    )
    criterios_ga = [
        'Seguimiento y distribución de correspondencia',
        'Seguimiento y distribución de insumos/consumibles',
        'Cumplimiento de normas internas',
        'HPIR y actualizaciones',
        'Implementaciones administrativas actualizadas',
        'Reporting / Informe mensual',
        'Cuadro de vehículos / Responsabilidad',
        'Habilitación de servicios',
        'Actualización de registros/base de datos',
        'Cierre de servicios / Capacitaciones',
        'Control de metrados por perforar',
        'Monto de metros por perforar/darr',
        'Actualización de servicios y refacciones',
    ]
    for i, nombre in enumerate(criterios_ga, 1):
        CriterioBono.objects.create(concepto=sec_ga, nombre=nombre, orden=i, activo=True)

    # Sección 3: Gestión Operativa (40%)
    sec_go = ConceptoBono.objects.create(
        tipo_bono=bono_adm, codigo='GO', nombre='Gestión Operativa',
        es_obligatorio=True, peso_default=40, orden=3,
    )
    criterios_go = [
        'Coordinación general con residencia',
        'Soporte operativo diario',
        'Gestión de requerimientos',
        'Control de inventario local',
        'Cumplimiento de entregables',
    ]
    for i, nombre in enumerate(criterios_go, 1):
        CriterioBono.objects.create(concepto=sec_go, nombre=nombre, orden=i, activo=True)

    # ==========================================================
    # CUADRO RESIDENTES — Residentes + Asist. de Residentes
    # ==========================================================
    bono_res = TipoBono.objects.create(
        codigo='RES',
        nombre='Bono Residentes',
        categoria='REMUNERATIVO',
        tipo_calculo='MULTI_CONCEPTO',
        descripcion='Bono para personal de residencia: Residentes y Asistentes de Residente.',
        es_sistema=True,
        activo=True,
        cargos_aplicables=['RESIDENTE', 'ASISTENTE DE RESIDENTE'],
    )

    sec_r1 = ConceptoBono.objects.create(
        tipo_bono=bono_res, codigo='PROD', nombre='Producción',
        es_obligatorio=True, peso_default=40, orden=1,
    )
    sec_r2 = ConceptoBono.objects.create(
        tipo_bono=bono_res, codigo='SEG', nombre='Seguridad',
        es_obligatorio=True, peso_default=30, orden=2,
    )
    sec_r3 = ConceptoBono.objects.create(
        tipo_bono=bono_res, codigo='GEST', nombre='Gestión',
        es_obligatorio=True, peso_default=30, orden=3,
    )

    # ==========================================================
    # CUADRO OPERADORES — Perforistas + Ayudantes
    # ==========================================================
    bono_ope = TipoBono.objects.create(
        codigo='OPE',
        nombre='Bono Operadores',
        categoria='REMUNERATIVO',
        tipo_calculo='MULTI_CONCEPTO',
        descripcion='Bono para personal operativo: Perforistas y Ayudantes.',
        es_sistema=True,
        activo=True,
        cargos_aplicables=['PERFORISTA', 'AYUDANTE'],
    )

    sec_o1 = ConceptoBono.objects.create(
        tipo_bono=bono_ope, codigo='PROD', nombre='Producción',
        es_obligatorio=True, peso_default=50, orden=1,
    )
    sec_o2 = ConceptoBono.objects.create(
        tipo_bono=bono_ope, codigo='SEG', nombre='Seguridad',
        es_obligatorio=True, peso_default=30, orden=2,
    )
    sec_o3 = ConceptoBono.objects.create(
        tipo_bono=bono_ope, codigo='CUMPL', nombre='Cumplimiento',
        es_obligatorio=True, peso_default=20, orden=3,
    )


def reverse_seed(apps, schema_editor):
    TipoBono = apps.get_model('drilling', 'TipoBono')
    TipoBono.objects.filter(es_sistema=True, codigo__in=['ADM', 'RES', 'OPE']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0089_create_payroll_models_v2'),
    ]

    operations = [
        migrations.RunPython(seed_bonos_sistema, reverse_seed),
    ]
