# Generated by Django 5.0.7 on 2026-04-14 18:41

from django.db import migrations


def seed_bonos_sistema(apps, schema_editor):
    """Crea los 4 tipos de bono del sistema + sus conceptos."""
    TipoBono = apps.get_model('drilling', 'TipoBono')
    ConceptoBono = apps.get_model('drilling', 'ConceptoBono')

    # B1 — BONO FIJO (Remunerativo, cálculo fijo)
    b1 = TipoBono.objects.create(
        codigo='B1',
        nombre='Bono Fijo',
        categoria='REMUNERATIVO',
        tipo_calculo='FIJO',
        descripcion='Bono remunerativo fijo. Se calcula: (monto_mensual / días_base) × días_trabajados.',
        es_sistema=True,
        activo=True,
    )

    # B2 — BONO CONDUCTORES (Remunerativo, multi-concepto)
    b2 = TipoBono.objects.create(
        codigo='B2',
        nombre='Bono Conductores',
        categoria='REMUNERATIVO',
        tipo_calculo='MULTI_CONCEPTO',
        descripcion='Bono remunerativo para conductores. Se evalúa por conceptos: Eficiencia y Cuidado del Equipo.',
        es_sistema=True,
        activo=True,
    )
    ConceptoBono.objects.create(
        tipo_bono=b2, codigo='EFICIENCIA', nombre='Eficiencia',
        es_obligatorio=True, peso_default=50, orden=1,
    )
    ConceptoBono.objects.create(
        tipo_bono=b2, codigo='CUIDADO_EQUIPO', nombre='Cuidado del Equipo',
        es_obligatorio=True, peso_default=50, orden=2,
    )

    # B3 — BONO CUMPLIMIENTO (Remunerativo, multi-concepto)
    b3 = TipoBono.objects.create(
        codigo='B3',
        nombre='Bono Cumplimiento',
        categoria='REMUNERATIVO',
        tipo_calculo='MULTI_CONCEPTO',
        descripcion='Bono remunerativo por cumplimiento. Conceptos: Producción, Seguridad, Costo por Metro (obligatorios); Valorización y Resultados Operativos (opcionales).',
        es_sistema=True,
        activo=True,
    )
    ConceptoBono.objects.create(
        tipo_bono=b3, codigo='PRODUCCION', nombre='Producción',
        es_obligatorio=True, peso_default=30, orden=1,
    )
    ConceptoBono.objects.create(
        tipo_bono=b3, codigo='SEGURIDAD', nombre='Seguridad',
        es_obligatorio=True, peso_default=30, orden=2,
    )
    ConceptoBono.objects.create(
        tipo_bono=b3, codigo='COSTO_METRO', nombre='Costo por Metro',
        es_obligatorio=True, peso_default=20, orden=3,
    )
    ConceptoBono.objects.create(
        tipo_bono=b3, codigo='VALORIZACION', nombre='Valorización',
        es_obligatorio=False, peso_default=10, orden=4,
    )
    ConceptoBono.objects.create(
        tipo_bono=b3, codigo='RESULTADOS_OP', nombre='Resultados Operativos',
        es_obligatorio=False, peso_default=10, orden=5,
    )

    # B4 — BONO EXTRAORDINARIO (Extraordinario, por día)
    b4 = TipoBono.objects.create(
        codigo='B4',
        nombre='Bono Extraordinario',
        categoria='EXTRAORDINARIO',
        tipo_calculo='POR_DIA',
        descripcion='Bono extraordinario basado en días trabajados. Se calcula: monto_por_día × días_trabajados.',
        es_sistema=True,
        activo=True,
    )


def reverse_seed(apps, schema_editor):
    TipoBono = apps.get_model('drilling', 'TipoBono')
    TipoBono.objects.filter(es_sistema=True, codigo__in=['B1', 'B2', 'B3', 'B4']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0089_create_payroll_models'),
    ]

    operations = [
        migrations.RunPython(seed_bonos_sistema, reverse_seed),
    ]
