# Generated by Django 5.0.7 on 2026-04-15 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0090_seed_bonos_sistema_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciadiaria',
            name='trabajador',
            field=models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_diarias', to='drilling.trabajador', verbose_name='Trabajador'),
        ),
        migrations.CreateModel(
            name='ProgramacionEMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinica', models.CharField(choices=[('NATCLAR', 'Natclar'), ('PULSO_SALUD', 'Pulso Salud'), ('SANTA_CRUZ', 'Santa Cruz')], max_length=30, verbose_name='Clínica')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('fecha', models.DateField(verbose_name='Fecha Programada')),
                ('tipo_examen', models.CharField(choices=[('PERIODICO', 'Periódico'), ('RETIRO', 'Retiro')], max_length=20, verbose_name='Tipo de Examen')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_emo_creadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_emo', to='drilling.trabajador')),
            ],
            options={
                'verbose_name': 'Programación EMO',
                'verbose_name_plural': 'Programaciones EMO',
                'db_table': 'programacion_emo',
                'ordering': ['-fecha'],
            },
        ),
    ]
