# Generated by Django 5.0.7 on 2026-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0091_add_programacion_emo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='sueldo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sueldo mensual del trabajador. Será sincronizado desde la API más adelante.', max_digits=10, null=True, verbose_name='Sueldo'),
        ),
    ]
