# Generated by Django 5.0.7 on 2026-04-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0092_add_sueldo_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR_GENERAL', 'Administrador General del Sistema'), ('ADMINISTRADOR', 'Administrador de Contrato'), ('LOGISTICO', 'Logístico'), ('RESIDENTE', 'Residente'), ('CONTROL_PROYECTOS', 'Control de Proyectos'), ('GERENCIA', 'Gerencia'), ('GERENTE_GENERAL', 'Gerente General'), ('HEADCOUNT', 'Gestión de Personal y Headcount'), ('JEFE_MANTENIMIENTO', 'Jefe de Mantenimiento'), ('MANTENIMIENTO', 'Mantenimiento de Contrato'), ('NOMINAS', 'Nóminas y Planillas'), ('MANAGER_CONTRATO', 'Manager de Contrato'), ('SUPERVISOR', 'Supervisor')], default='ADMINISTRADOR', help_text='Define los permisos y accesos del usuario', max_length=30, verbose_name='Rol del usuario'),
        ),
    ]
