# Generated by Django 5.0.7 on 2026-04-17 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0096_crear_contrato_servicio_ddh_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstructuraSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_contratado', models.CharField(help_text='Nombre del cargo (debe coincidir con el campo cargo del Trabajador)', max_length=200, verbose_name='Cargo Contratado')),
                ('sueldo_basico', models.DecimalField(decimal_places=2, default=0, help_text='Sueldo base mensual para este cargo', max_digits=10, verbose_name='Sueldo Básico (S/)')),
                ('bono_por_metraje', models.DecimalField(decimal_places=2, default=0, help_text='Monto del bono por cumplimiento de metraje', max_digits=10, verbose_name='Bono por Metraje (S/)')),
                ('metraje_base', models.DecimalField(decimal_places=2, default=0, help_text='Metraje base requerido para acceder al bono por metraje', max_digits=10, verbose_name='Metraje Base (m)')),
                ('bonificacion_area', models.DecimalField(decimal_places=2, default=0, help_text='Bonificación adicional por zona o área de trabajo', max_digits=10, verbose_name='Bonificación Área (S/)')),
                ('version', models.PositiveIntegerField(default=1, help_text='Número de versión actual (se incrementa en cada cambio)', verbose_name='Versión')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estructuras_salariales', to='drilling.contrato', verbose_name='Contrato')),
                ('contrato_servicio', models.ForeignKey(help_text='Centro de costo / servicio del contrato', on_delete=django.db.models.deletion.CASCADE, related_name='estructuras_salariales', to='drilling.contratoservicio', verbose_name='CTR (Centro de Costo)')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estructuras_salariales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Estructura Salarial',
                'verbose_name_plural': 'Estructuras Salariales',
                'db_table': 'payroll_estructura_salarial',
                'ordering': ['contrato__nombre_contrato', 'contrato_servicio__tipo_servicio', 'cargo_contratado'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstructuraSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Versión')),
                ('sueldo_basico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo Básico (S/)')),
                ('bono_por_metraje', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bono por Metraje (S/)')),
                ('metraje_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Metraje Base (m)')),
                ('bonificacion_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonificación Área (S/)')),
                ('motivo_cambio', models.TextField(blank=True, help_text='Descripción del motivo de la modificación', verbose_name='Motivo del Cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='drilling.estructurasalarial', verbose_name='Estructura Salarial')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estructura_salarial', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Historial Estructura Salarial',
                'verbose_name_plural': 'Historial Estructuras Salariales',
                'db_table': 'payroll_historial_estructura_salarial',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='estructurasalarial',
            index=models.Index(fields=['contrato', 'activo'], name='payroll_est_contrat_03694e_idx'),
        ),
        migrations.AddIndex(
            model_name='estructurasalarial',
            index=models.Index(fields=['cargo_contratado'], name='payroll_est_cargo_c_981a67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estructurasalarial',
            unique_together={('contrato', 'contrato_servicio', 'cargo_contratado')},
        ),
        migrations.AddIndex(
            model_name='historialestructurasalarial',
            index=models.Index(fields=['estructura', '-version'], name='payroll_his_estruct_2f7e6a_idx'),
        ),
    ]
