# Generated by Django 5.0.7 on 2026-04-23 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0103_conceptobono_tabla_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDiasMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dias', models.PositiveIntegerField(default=0, verbose_name='Total días asignado')),
                ('primera_asignacion', models.DateField(blank=True, null=True, verbose_name='Primera fecha')),
                ('ultima_asignacion', models.DateField(blank=True, null=True, verbose_name='Última fecha')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen Días por Máquina',
                'verbose_name_plural': 'Resumen Días por Máquina',
                'db_table': 'resumen_dias_maquina',
                'ordering': ['-total_dias'],
            },
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_bono_tr_8b3218_idx',
            old_name='payroll_hist_bono_trab_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_trabaja_b67e36_idx',
            old_name='payroll_hist_trab_tipo_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_periodo_69b074_idx',
            old_name='payroll_hist_periodo_tipo_idx',
        ),
        migrations.AlterField(
            model_name='configuracionbonocontrato',
            name='tipo_calculo_por_trabajador',
            field=models.JSONField(blank=True, default=dict, help_text='DNI → "metraje" | "cumplimiento". Ej: {"12345678": "metraje"}. Vacío o sin clave = trabajador calcula por cumplimiento KPI (lógica normal).', verbose_name='Tipo de Cálculo por Trabajador'),
        ),
        migrations.AddField(
            model_name='resumendiasmaquina',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_dias_trabajadores', to='drilling.maquina'),
        ),
        migrations.AddField(
            model_name='resumendiasmaquina',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_dias_maquina', to='drilling.trabajador'),
        ),
        migrations.AddIndex(
            model_name='resumendiasmaquina',
            index=models.Index(fields=['trabajador'], name='resumen_dia_trabaja_d76e29_idx'),
        ),
        migrations.AddIndex(
            model_name='resumendiasmaquina',
            index=models.Index(fields=['maquina'], name='resumen_dia_maquina_df6b6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumendiasmaquina',
            unique_together={('trabajador', 'maquina')},
        ),
    ]
