# Generated by Django 5.0.7 on 2026-04-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0104_resumen_dias_maquina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estructurasalarial',
            options={'ordering': ['contrato__nombre_contrato', 'contrato_servicio__tipo_servicio', 'cargo_contratado', 'maquina__nombre'], 'verbose_name': 'Estructura Salarial', 'verbose_name_plural': 'Estructuras Salariales'},
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_bono_tr_8b3218_idx',
            old_name='payroll_hist_bono_trab_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_trabaja_b67e36_idx',
            old_name='payroll_hist_trab_tipo_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_periodo_69b074_idx',
            old_name='payroll_hist_periodo_tipo_idx',
        ),
        migrations.AlterUniqueTogether(
            name='estructurasalarial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estructurasalarial',
            name='maquina',
            field=models.ForeignKey(blank=True, help_text='Máquina específica a la que aplica esta estructura. Dejar vacío para aplicar a todas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estructuras_salariales', to='drilling.maquina', verbose_name='Máquina'),
        ),
        migrations.AlterField(
            model_name='configuracionbonocontrato',
            name='tipo_calculo_por_trabajador',
            field=models.JSONField(blank=True, default=dict, help_text='DNI → "metraje" | "cumplimiento". Ej: {"12345678": "metraje"}. Vacío o sin clave = trabajador calcula por cumplimiento KPI (lógica normal).', verbose_name='Tipo de Cálculo por Trabajador'),
        ),
        migrations.AddConstraint(
            model_name='estructurasalarial',
            constraint=models.UniqueConstraint(condition=models.Q(('maquina__isnull', True)), fields=('contrato', 'contrato_servicio', 'cargo_contratado'), name='unique_estructura_sin_maquina'),
        ),
        migrations.AddConstraint(
            model_name='estructurasalarial',
            constraint=models.UniqueConstraint(condition=models.Q(('maquina__isnull', False)), fields=('contrato', 'contrato_servicio', 'cargo_contratado', 'maquina'), name='unique_estructura_con_maquina'),
        ),
    ]
