# Generated by Django 5.0.7 on 2026-04-30 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0106_asignacionestructurasalarial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('concepto', models.CharField(choices=[('BASICO', 'Sueldo Básico'), ('BONOS_REMUNERATIVOS', 'Bonos Remunerativos'), ('BONOS_EXTRAORDINARIOS', 'Bonos Extraordinarios'), ('BONOS', 'Total Bonos'), ('OTRO', 'Otro')], default='BONOS', max_length=30, verbose_name='Concepto')),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Presupuestado (S/)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Presupuesto de Planilla',
                'verbose_name_plural': 'Presupuestos de Planilla',
                'db_table': 'payroll_presupuesto_planilla',
                'ordering': ['-anio', '-mes', 'contrato__nombre_contrato'],
            },
        ),
        migrations.AddField(
            model_name='presupuestoplanilla',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_planilla', to='drilling.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='presupuestoplanilla',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_planilla_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterUniqueTogether(
            name='presupuestoplanilla',
            unique_together={('contrato', 'anio', 'mes', 'concepto')},
        ),
    ]
