# Generated by Django 5.0.7 on 2026-05-04 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0107_add_presupuesto_planilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cese', models.DateField(verbose_name='Fecha de Cese')),
                ('tipo_baja', models.CharField(choices=[('RENUNCIA', 'Renuncia voluntaria'), ('DESPIDO', 'Despido'), ('FIN_CONTRATO', 'Fin de contrato'), ('JUBILACION', 'Jubilación'), ('FALLECIMIENTO', 'Fallecimiento'), ('OTRO', 'Otro')], default='FIN_CONTRATO', max_length=20, verbose_name='Tipo de Baja')),
                ('bonos_ultimo_periodo', models.DecimalField(decimal_places=2, default=0, help_text='Monto de bonos del período parcial de cese', max_digits=12, verbose_name='Bonos Último Período (S/)')),
                ('vacaciones_pendientes_dias', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Días de Vacaciones Pendientes')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liquidación de Trabajador',
                'verbose_name_plural': 'Liquidaciones de Trabajadores',
                'db_table': 'payroll_liquidacion_trabajador',
                'ordering': ['-fecha_cese', 'trabajador__apepat'],
            },
        ),
        migrations.RenameIndex(
            model_name='asignacionestructurasalarial',
            new_name='payroll_asi_contrat_32b47f_idx',
            old_name='payroll_asi_contrat_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='asignacionestructurasalarial',
            new_name='payroll_asi_trabaja_795d03_idx',
            old_name='payroll_asi_trabaja_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_bono_tr_8b3218_idx',
            old_name='payroll_hist_bono_trab_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_trabaja_b67e36_idx',
            old_name='payroll_hist_trab_tipo_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_periodo_69b074_idx',
            old_name='payroll_hist_periodo_tipo_idx',
        ),
        migrations.AddField(
            model_name='liquidaciontrabajador',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='liquidaciontrabajador',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_trabajadores', to='drilling.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='liquidaciontrabajador',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='liquidaciontrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='drilling.trabajador', verbose_name='Trabajador'),
        ),
    ]
