# Generated by Django 5.0.7 on 2026-05-06 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0108_liquidacion_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionbonocontrato',
            name='tipo_calculo_default',
            field=models.CharField(choices=[('cumplimiento', 'Cumplimiento KPI (default)'), ('metraje', 'Metraje (todos por metro)'), ('ambos', 'Ambos (cumplimiento + metraje)')], default='cumplimiento', help_text='Tipo de cálculo aplicado a trabajadores sin entrada en tipo_calculo_por_trabajador.', max_length=20, verbose_name='Tipo de Cálculo por Defecto'),
        ),
        migrations.AlterField(
            model_name='configuracionbonocontrato',
            name='tipo_calculo_por_trabajador',
            field=models.JSONField(blank=True, default=dict, help_text='DNI → "metraje" | "cumplimiento". Ej: {"12345678": "metraje"}. Vacío o sin clave = usa tipo_calculo_default.', verbose_name='Tipo de Cálculo por Trabajador'),
        ),
    ]
