# Generated by Django 5.0.7 on 2026-05-06 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0108_liquidacion_trabajador'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asignacionestructurasalarial',
            new_name='payroll_asi_contrat_32b47f_idx',
            old_name='payroll_asi_contrat_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='asignacionestructurasalarial',
            new_name='payroll_asi_trabaja_795d03_idx',
            old_name='payroll_asi_trabaja_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_bono_tr_8b3218_idx',
            old_name='payroll_hist_bono_trab_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_trabaja_b67e36_idx',
            old_name='payroll_hist_trab_tipo_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historialbonotrabajador',
            new_name='payroll_his_periodo_69b074_idx',
            old_name='payroll_hist_periodo_tipo_idx',
        ),
        migrations.AddField(
            model_name='configuracionbonocontrato',
            name='tipo_calculo_default',
            field=models.CharField(choices=[('cumplimiento', 'Cumplimiento KPI (default)'), ('metraje', 'Metraje (todos por metro)'), ('ambos', 'Ambos (cumplimiento + metraje)')], default='cumplimiento', help_text='Tipo de cálculo aplicado a trabajadores sin entrada en tipo_calculo_por_trabajador.', max_length=20, verbose_name='Tipo de Cálculo por Defecto'),
        ),
        migrations.AlterField(
            model_name='bonotrabajador',
            name='dias_trabajados',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Días Trabajados'),
        ),
        migrations.AlterField(
            model_name='configuracionbonocontrato',
            name='tipo_calculo_por_trabajador',
            field=models.JSONField(blank=True, default=dict, help_text='DNI → "metraje" | "cumplimiento". Ej: {"12345678": "metraje"}. Vacío o sin clave = usa tipo_calculo_default.', verbose_name='Tipo de Cálculo por Trabajador'),
        ),
        migrations.AlterField(
            model_name='historialbonotrabajador',
            name='dias_trabajados',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Días Trabajados'),
        ),
        migrations.AlterField(
            model_name='tareoentry',
            name='estado',
            field=models.CharField(choices=[('TRABAJO', 'Trabajo'), ('TD', 'Turno Día'), ('TN', 'Turno Noche'), ('DESCANSO', 'Descanso'), ('MDL', 'Medio Día Libre'), ('FALTA', 'Falta'), ('VACACIONES', 'Vacaciones'), ('PERMISO', 'Permiso')], db_index=True, default='TRABAJO', max_length=20),
        ),
    ]
