#!/bin/bash
# Comandos rápidos para desplegar desde tu laptop

echo "======================================================================"
echo "PREPARANDO CÓDIGO PARA DESPLIEGUE"
echo "======================================================================"

# Verificar estado de Git
echo ""
echo "📋 Estado actual de Git:"
git status

echo ""
echo "======================================================================"
echo "Archivos listos para commit:"
echo "======================================================================"
echo "  ✅ drilling/views.py (cache + optimizaciones)"
echo "  ✅ drilling/models.py (HistorialBroca + métodos optimizados)"
echo "  ✅ settings.py (connection pooling)"
echo "  ✅ requirements.txt (django-db-connection-pool)"
echo "  ✅ .env.production (template para servidor)"
echo "  ✅ deploy.sh (script de despliegue)"
echo "  ✅ DESPLIEGUE.md (documentación)"
echo "  ✅ preload_cache.py (precarga de cache)"
echo ""

echo "======================================================================"
echo "Comandos para desplegar:"
echo "======================================================================"
echo ""
echo "1️⃣  Commit y push desde tu laptop:"
echo "    git add ."
echo "    git commit -m 'Optimizaciones de performance: cache, connection pooling, bulk operations'"
echo "    git push origin main"
echo ""
echo "2️⃣  Conectar al servidor:"
echo "    ssh root@138.197.203.247"
echo ""
echo "3️⃣  En el servidor, ir al proyecto y ejecutar:"
echo "    cd /ruta/al/proyecto/perforaciones_diamantinas"
echo "    git pull origin main"
echo "    chmod +x deploy.sh"
echo "    ./deploy.sh"
echo ""
echo "4️⃣  Reiniciar servicios:"
echo "    sudo systemctl restart gunicorn"
echo "    sudo systemctl restart nginx"
echo ""
echo "======================================================================"
echo "📊 Mejoras esperadas en PRODUCCIÓN (servidor con DB local):"
echo "======================================================================"
echo "  • Latencia queries: 160ms → <5ms (97% más rápido)"
echo "  • Carga formulario: 1300ms → ~50ms (96% más rápido)"
echo "  • Creación turno: 800ms → ~100ms (87% más rápido)"
echo "  • Queries formulario: 9 → 6 (33% menos)"
echo ""
